package br.filipov.values.o;

/**
 * @author Marcelo Aparecido Filipov
 * @since 2014
 */
public enum OcupacaoValues {

	ACOUGUEIRO(151,0,"ACOUGUEIRO"),
	ACUPUNTURISTA(152,0,"ACUPUNTURISTA"),
	ADMINISTRADOR(21,0,"ADMINISTRADOR"),
	ADMINISTRADOR_DE_COMARCA(272,0,"ADMINISTRADOR DE COMARCA"),
	ADMINISTRADOR_DE_TRIBUNAL(334,0,"ADMINISTRADOR DE TRIBUNAL"),
	ADVOGADO(25,0,"ADVOGADO"),
	AERONAUTA(153,0,"AERONAUTA"),
	AEROVIARIO(154,0,"AEROVIARIO"),
	AGENCIADOR_DE_PROPAGANDA(90,0,"AGENCIADOR DE PROPAGANDA"),
	AGENTE_ADMINISTRATIVO(71,0,"AGENTE ADMINISTRATIVO"),
	AGENTE_COMUNITARIO_DE_SAUDE(322,0,"AGENTE COMUNITARIO DE SAUDE"),
	AGENTE_DE_SERVICOS_FUNERARIOS_E_EMBALSAMADOR(112,0,"AGENTE DE SERVICOS FUNERARIOS E EMBALSAMADOR"),
	AGENTE_DE_VIAGEM_E_GUIA_DE_TURISMO(111,0,"AGENTE DE VIAGEM E GUIA DE TURISMO"),
	AGRICULTOR(116,0,"AGRICULTOR"),
	AGRIMENSOR(258,0,"AGRIMENSOR"),
	AGRONOMO(3,0,"AGRONOMO"),
	AGROPECUARISTA(269,0,"AGROPECUARISTA"),
	ALFAIATE(108,0,"ALFAIATE"),
	AMBULANTE(242,12,"AMBULANTE"),
	ANALISTA(243,0,"ANALISTA"),
	ANALISTA_DE_SISTEMA(22,0,"ANALISTA DE SISTEMA"),
	ANTIQUARIO(237,0,"ANTIQUARIO"),
	ANTROPOLOGO(160,0,"ANTROPOLOGO"),
	APICULTOR(238,0,"APICULTOR"),
	AQUICULTOR(290,0,"AQUICULTOR"),
	ARMEIRO(161,0,"ARMEIRO"),
	ARQUEOLOGO_E_MUSEOLOGO(227,0,"ARQUEOLOGO E MUSEOLOGO"),
	ARQUITETO_OU_PAISAGISTA(2,0,"ARQUITETO OU PAISAGISTA"),
	ARTESAO(162,0,"ARTESAO"),
	ARTISTA_PLASTICO(163,0,"ARTISTA PLASTICO"),
	ASSISTENTE_SOCIAL(28,0,"ASSISTENTE SOCIAL"),
	ASTROLOGO(164,0,"ASTROLOGO"),
	ASTRONOMO(24,0,"ASTRONOMO"),
	ATLETA_PROFISSIONAL_E_TECNICO_EM_DESPORTOS(52,0,"ATLETA PROFISSIONAL E TECNICO EM DESPORTOS"),
	ATOR_E_DIRETOR_DE_ESPETACULOS_PUBLICOS(46,0,"ATOR E DIRETOR DE ESPETACULOS PUBLICOS"),
	AUXILIAR_DE_ENFERMAGEM(278,0,"AUXILIAR DE ENFERMAGEM"),
	AUXILIAR_DE_ESCRITORIO_E_ASSEMELHADOS(83,0,"AUXILIAR DE ESCRITORIO E ASSEMELHADOS"),
	AUXILIAR_DE_LABORATORIO_E_RAIOS_X(113,0,"AUXILIAR DE LABORATORIO E RAIOS X"),
	AUXILIAR_DE_NUTRICAO(289,0,"AUXILIAR DE NUTRICAO"),
	AUXILIAR_DE_SERVICOS_GERAIS(293,0,"AUXILIAR DE SERVICOS GERAIS"),
	AVICULTOR(239,0,"AVICULTOR"),
	BANCARIO_E_ECONOMIARIO(84,0,"BANCARIO E ECONOMIARIO"),
	BARBEIRO(97,0,"BARBEIRO, CABELEIREIRO, MANICURE E PEDICURE"),
	BIBLIOTECARIO_OU_ARQUIVISTA(29,0,"BIBLIOTECARIO OU ARQUIVISTA"),
	BIOFISICO(166,0,"BIOFISICO"),
	BIOLOGO_OU_BIOMEDICO(14,0,"BIOLOGO OU BIOMEDICO"),
	BIOQUIMICO(167,0,"BIOQUIMICO"),
	BOLSISTA_MESTRADO_DOUTORADO(323,15,"BOLSISTA MESTRADO/DOUTORADO"),
	BOLSISTA_OUTROS(326,16,"BOLSISTA OUTROS"),
	BOMBEIRO_E_INSTALADOR_DE_GAS(107,0,"BOMBEIRO E INSTALADOR DE GAS, AGUA, ESGOTO E ASSEMELHADO"),
	BORRACHEIRO(168,0,"BORRACHEIRO"),
	CANTOR_E_COMPOSITOR(47,0,"CANTOR E COMPOSITOR"),
	CAPITALISTA_RENTISTA(244,0,"CAPITALISTA/RENTISTA"),
	CARTEIRO(169,0,"CARTEIRO"),
	CENOGRAFO(184,0,"CENOGRAFO"),
	CERAMISTA(245,0,"CERAMISTA"),
	CHAVEIRO(171,0,"CHAVEIRO"),
	COBRADOR_DE_TRANSPORTE_COLETIVO(276,0,"COBRADOR DE TRANSPORTE COLETIVO"),
	COMERCIARIO(173,0,"COMERCIARIO"),
	COMUNICOLOGO(30,0,"COMUNICOLOGO"),
	CONSENHEIRO_TUTELAR(341,0,"CONSENHEIRO TUTELAR"),
	CONSULTOR_LEGISLATIVO(318,0,"CONSULTOR LEGISLATIVO"),
	CONTADOR(20,0,"CONTADOR"),
	COREOGRAFO_E_BAILARINO(49,0,"COREOGRAFO E BAILARINO"),
	CORREGEDOR(319,13,"CORREGEDOR"),
	CORRETOR(88,0,"CORRETOR"),
	COSTUREIRO(226,0,"COSTUREIRO"),
	COZINHEIRO(98,0,"COZINHEIRO, COPEIRO, GARCOM, BARMEN E CAMAREIRO"),
	DECORADOR(60,0,"DECORADOR"),
	DEFENSOR_PUBLICO(330,0,"DEFENSOR PUBLICO"),
	DELEGADO_DE_POLICIA(67,4,"DELEGADO DE POLICIA"),
	DEPUTADO_ESTADUAL_DISTRITAL(309,13,"DEPUTADO ESTADUAL/DISTRITAL"),
	DEPUTADO_FEDERAL(308,13,"DEPUTADO FEDERAL"),
	DESEMBARGADOR(271,0,"DESEMBARGADOR"),
	DESENHISTA(998,0,"DESENHISTA"),
	DESENHISTA_COMERCIAL(59,0,"DESENHISTA COMERCIAL"),
	DESENHISTA_INDUSTRIAL(5,0,"DESENHISTA INDUSTRIAL"),
	DESENHISTA_TECNICO(44,0,"DESENHISTA TECNICO"),
	DESPACHANTE(110,0,"DESPACHANTE, INCLUSIVE O ADUANEIRO"),
	DETETIVE_PARTICULAR(298,0,"DETETIVE PARTICULAR"),
	DIPLOMATA(65,0,"DIPLOMATA"),
	DISCOTECARIO(333,0,"DISCOTECARIO, VIDEOTECARIO E AFINS"),
	DO_LAR(200,11,"DO LAR"),
	ECOLOGISTA(175,0,"ECOLOGISTA"),
	ECONOMISTA(17,0,"ECONOMISTA"),
	ELETRICISTA_E_ASSEMELHADOS(123,0,"ELETRICISTA E ASSEMELHADOS"),
	ELETRICITARIO(176,0,"ELETRICITARIO"),
	EMPREGADO_DOMESTICO(115,0,"EMPREGADO DOMESTICO"),
	EMPRESARIO(78,0,"EMPRESARIO"),
	EMPRESARIO_E_PRODUTOR_DE_ESPETACULOS_PUBLICOS(45,0,"EMPRESARIO E PRODUTOR DE ESPETACULOS PUBLICOS"),
	ENFERMEIRO(11,0,"ENFERMEIRO"),
	ENGENHEIRO(1,0,"ENGENHEIRO"),
	ESCREVENTE_AUXILIAR_DE_CARTORIO(281,0,"ESCREVENTE/AUXILIAR DE CARTORIO"),
	ESCRITOR(177,0,"ESCRITOR"),
	ESCULTOR_PINTOR_OU_ASSEMELHADO(58,0,"ESCULTOR/PINTOR OU ASSEMELHADO"),
	ESTAGIARIO_E_ASSEMELHADOS(150,10,"ESTAGIARIO E ASSEMELHADOS"),
	ESTATISTICO(18,0,"ESTATISTICO"),
	ESTETICISTA(292,0,"ESTETICISTA"),
	ESTIVADOR(114,0,"ESTIVADOR, CARREGADOR, EMBALADOR E ASSEMELHADOS"),
	ESTUDANTE(179,11,"ESTUDANTE"),
	FARMACEUTICO(15,0,"FARMACEUTICO"),
	FAXINEIRO(280,0,"FAXINEIRO"),
	FEIRANTE(93,0,"FEIRANTE"),
	FERRAMENTEIRO(180,0,"FERRAMENTEIRO"),
	FERROVIARIO(283,0,"FERROVIARIO"),
	FILOLOGO(181,0,"FILOLOGO"),
	FILOSOFO(182,0,"FILOSOFO"),
	FISCAL(66,0,"FISCAL, AUDITOR E ASSEMELHADOS"),
	FISICO(6,0,"FISICO"),
	FISIOTERAPEUTA_OU_TERAPEUTA_OCUPACIONAL(12,0,"FISIOTERAPEUTA OU TERAPEUTA OCUPACIONAL"),
	FLORICULTOR(197,0,"FLORICULTOR"),
	FONOAUDIOLOGO(16,0,"FONOAUDIOLOGO"),
	FOTOGRAFO(198,0,"FOTOGRAFO"),
	FRENTISTA(275,1,"FRENTISTA"),
	FUNILEIRO(246,0,"FUNILEIRO"),
	GARI_OU_VARREDOR_DE_LOGRADOUROS_PUBLICOS(294,0,"GARI OU VARREDOR DE LOGRADOUROS PUBLICOS"),
	GARIMPEIRO(120,0,"GARIMPEIRO"),
	GEOGRAFO(23,0,"GEOGRAFO"),
	GEOLOGO(7,0,"GEOLOGO"),
	GOVERNADOR_DE_ESTADO_DISTRITO_FEDERAL(306,13,"GOVERNADOR DE ESTADO/DISTRITO FEDERAL"),
	HISTORIADOR(247,0,"HISTORIADOR"),
	INDUSTRIARIO(248,0,"INDUSTRIARIO"),
	INSTRUTOR(279,0,"INSTRUTOR"),
	JARDINEIRO(342,0,"JARDINEIRO"),
	JOALHEIRO_E_OURIVES(137,0,"JOALHEIRO E OURIVES"),
	JORNALEIRO(92,0,"JORNALEIRO"),
	JORNALISTA(53,0,"JORNALISTA"),
	LANTERNEIRO_E_PINTOR_DE_VEICULOS(106,0,"LANTERNEIRO E PINTOR DE VEICULOS"),
	LEILOEIRO(89,0,"LEILOEIRO; AVALIADOR E ASSEMELHADOS"),
	LOCUTOR_E_COMENTARISTA_DE_RADIO_E_TELEVISAO_E_RADIALISTA(50,0,"LOCUTOR E COMENTARISTA DE RADIO E TELEVISAO E RADIALISTA"),
	MAGISTRADO(273,0,"MAGISTRADO"),
	MAQUINISTA_E_FOGUISTA_DE_EMBARCACOES(103,0,"MAQUINISTA E FOGUISTA DE EMBARCACOES;LOCOMOTIVAS E ASSEM"),
	MARCENEIRO_E_TRAB_ARTEFATOS_MADEIRA(133,0,"MARCENEIRO E TRAB.ARTEFATOS MADEIRA"),
	MARINHEIRO(102,0,"MARINHEIRO"),
	MASSAGISTA(240,0,"MASSAGISTA"),
	MATEMATICO_E_ATUARIO(19,0,"MATEMATICO E ATUARIO"),
	MECANICO_DE_MANUTENCAO_DE_MAQUINAS_INDUSTRIAIS(295,0,"MECANICO DE MANUTENCAO DE MAQUINAS INDUSTRIAIS"),
	MECANICO_DE_MANUTENCAO_DE_VEICULOS_AUTOMOTORES(104,0,"MECANICO DE MANUTENCAO DE VEICULOS AUTOMOTORES"),
	MEDICO(9,0,"MEDICO"),
	MENOR_SEM_ATIVIDADE(324,11,"MENOR SEM ATIVIDADE"),
	MERGULHADOR(320,0,"MERGULHADOR"),
	MESTRE_E_CONTRAMESTRE(121,0,"MESTRE E CONTRAMESTRE"),
	METALURGICO_E_SIDERURGICO(127,0,"METALURGICO E SIDERURGICO"),
	METEOROLOGISTA(228,0,"METEOROLOGISTA"),
	MILITAR_DAS_FORCAS_ARMADAS_AERONAUTICA(337,0,"MILITAR DAS FORCAS ARMADAS - AERONAUTICA"),
	MILITAR_DAS_FORCAS_ARMADAS_EXERCITO(335,0,"MILITAR DAS FORCAS ARMADAS - EXERCITO"),
	MILITAR_DAS_FORCAS_ARMADAS_MARINHA(336,0,"MILITAR DAS FORCAS ARMADAS - MARINHA"),
	MILITAR_EM_GERAL(74,0,"MILITAR EM GERAL"),
	MINISTRO_DE_ESTADO(305,13,"MINISTRO DE ESTADO"),
	MISSIONARIO(202,0,"MISSIONARIO"),
	MODELISTA_E_OU_CORTADOR_VESTUARIO(302,0,"MODELISTA E/OU CORTADOR - VESTUARIO"),
	MODELO_DE_MODAS(95,0,"MODELO DE MODAS"),
	MODISTA(203,0,"MODISTA"),
	MOTOCICLISTA_TRANSP_DE_MERCADORIAS_E_OU_ASSEMELHADOS(301,0,"MOTOCICLISTA (TRANSP. DE MERCADORIAS) E/OU ASSEMELHADOS"),
	MOTORISTA(999,0,"MOTORISTA"),
	MOTORISTA_DE_MAQUINAS_PESADAS(255,0,"MOTORISTA DE MAQUINAS PESADAS"),
	MOTORISTA_DE_VEICULOS_DE_TRANSPORTE_DE_CARGA(100,0,"MOTORISTA DE VEICULOS DE TRANSPORTE DE CARGA"),
	MOTORISTA_DE_VEICULOS_DE_TRANSPORTE_DE_PASSAGEIROS(99,0,"MOTORISTA DE VEICULOS DE TRANSPORTE DE PASSAGEIROS"),
	MUSICO(48,0,"MUSICO"),
	NUTRICIONISTA(229,0,"NUTRICIONISTA"),
	OCEANOGRAFO(204,0,"OCEANOGRAFO"),
	ODONTOLOGO(13,0,"ODONTOLOGO"),
	OFICIAL_DAS_FORCAS_ARMADAS_E_FORCAS_AUXILIARES(69,0,"OFICIAL DAS FORCAS ARMADAS E FORCAS AUXILIARES"),
	OFICIAL_DE_JUSTICA(316,0,"OFICIAL DE JUSTICA"),
	OLEIRO(205,0,"OLEIRO"),
	OPERADOR_DE_COMPUTADORES(206,0,"OPERADOR DE COMPUTADORES"),
	OPERADOR_DE_MAQUINAS_AGROPECUARIAS(287,0,"OPERADOR DE MAQUINAS AGROPECUARIAS"),
	OPERADOR_DE_TELEMARKETING(332,0,"OPERADOR DE TELEMARKETING"),
	OPTICO(249,0,"OPTICO"),
	ORNITOLOGO(250,0,"ORNITOLOGO"),
	PADEIRO(207,0,"PADEIRO"),
	PASTOR(208,0,"PASTOR"),
	PECUARISTA(117,0,"PECUARISTA"),
	PEDAGOGO(277,0,"PEDAGOGO"),
	PENSIONISTA(149,8,"PENSIONISTA"),
	PESCADOR(119,0,"PESCADOR"),
	PESCADOR_COM_FINS_COMERCIAIS(268,0,"PESCADOR COM FINS COMERCIAIS"),
	PESQ_PRODUC_DE_MUDAS_OU_SEMENT_FISCALIZADAS_CERTIFICADAS(259,0,"PESQ/PRODUC DE MUDAS OU SEMENT FISCALIZADAS/CERTIFICADAS"),
	PESQ_PRODUC_DE_SEMEM_PARA_INSEMINACAO_ARTIFICIAL(260,0,"PESQ/PRODUC DE SEMEM PARA INSEMINACAO ARTIFICIAL"),
	PILOTO_DE_AERONAVES(55,0,"PILOTO DE AERONAVES"),
	POLICIAL_CIVIL(209,0,"POLICIAL CIVIL"),
	PORTEIRO_DE_EDIFICIO(96,0,"PORTEIRO DE EDIFICIO ASCENSORISTA E GARAGISTA"),
	PORTUARIO(282,0,"PORTUARIO"),
	PREFEITO_MUNICIPAL(311,13,"PREFEITO MUNICIPAL"),
	PRESIDENTE_DA_REPUBLICA(303,13,"PRESIDENTE DA REPUBLICA"),
	PREST_SERV_DE_INSEMINACAO_ARTIFICIAL(263,0,"PREST SERV DE INSEMINACAO ARTIFICIAL, EM IMOVEL RURAL"),
	PREST_SERV_MECANIZAD(261,0,"PREST SERV MECANIZAD, NATURAL, RURAL INCLUSIVE PROTECAO SO"),
	PROCURADOR_DA_JUSTICA_E_ASSEMELHADOS(64,0,"PROCURADOR DA JUSTICA E ASSEMELHADOS"),
	PROFESSOR_DE_ENSINO_FUNDAMENTAL_E_MEDIO(34,0,"PROFESSOR DE ENSINO FUNDAMENTAL E MEDIO"),
	PROFESSOR_DE_ENSINO_SUPERIOR(33,0,"PROFESSOR DE ENSINO SUPERIOR"),
	PROFESSOR_DEMAIS(997,0,"PROFESSOR/DEMAIS"),
	PROFISSIONAL_DE_LETRAS_E_ARTES(32,0,"PROFISSIONAL DE LETRAS E ARTES"),
	PROGRAMADOR_DE_SISTEMA(210,0,"PROGRAMADOR DE SISTEMA"),
	PROMOTOR_DE_JUSTICA(310,13,"PROMOTOR DE JUSTICA"),
	PROMOTOR_DE_VENDAS_E_DEMONSTRADOR(94,0,"PROMOTOR DE VENDAS E DEMONSTRADOR"),
	PROTETICO(109,0,"PROTETICO"),
	PSICOLOGO(26,0,"PSICOLOGO"),
	PUBLICITARIO(54,0,"PUBLICITARIO"),
	QUIMICO(4,0,"QUIMICO"),
	RADIOTECNICO(211,0,"RADIOTECNICO"),
	REDATOR(241,0,"REDATOR"),
	RELACOES_PUBLICAS(31,0,"RELACOES PUBLICAS"),
	RELOJOEIRO(212,0,"RELOJOEIRO"),
	RENTISTA_OU_LOCADOR(339,0,"RENTISTA OU LOCADOR"),
	REPRESENTANTE_COMERCIAL(199,0,"REPRESENTANTE COMERCIAL"),
	RODOVIARIO(251,0,"RODOVIARIO"),
	SACERDOTE(213,0,"SACERDOTE"),
	SALVA_VIDAS_OU_BOMBEIRO_PARTICULAR_AUTONOMO(286,0,"SALVA-VIDAS OU BOMBEIRO PARTICULAR/AUTONOMO"),
	SAPATEIRO_E_DEMAIS_TRAB_DE_CALCADOS_E_ARTEFATOS_DE_COURO(135,0,"SAPATEIRO E DEMAIS TRAB DE CALCADOS E ARTEFATOS DE COURO"),
	SECRETARIO_ESTADUAL(314,13,"SECRETARIO ESTADUAL"),
	SECRETARIO_FEDERAL(313,13,"SECRETARIO FEDERAL"),
	SECRETARIO_MUNICIPAL(315,13,"SECRETARIO MUNICIPAL"),
	SECRETARIO_ESTENOGRAFO_DATIL_RECEP_TELEF_TRAB_ASSEMELHAD(82,0,"SECRETARIO/ESTENOGRAFO/DATIL/RECEP/TELEF TRAB ASSEMELHAD"),
	SECURITARIO(85,0,"SECURITARIO"),
	SEGURANCA_VIGILANTE(214,0,"SEGURANCA/VIGILANTE"),
	SENADOR_DA_REPUBLICA(307,13,"SENADOR DA REPUBLICA"),
	SERRALHEIRO(215,0,"SERRALHEIRO"),
	SERVENTUARIO_DE_JUSTICA(72,0,"SERVENTUARIO DE JUSTICA"),
	SERVIDOR_PUBLICO_ESTADUAL(76,0,"SERVIDOR PUBLICO ESTADUAL"),
	SERVIDOR_PUBLICO_FEDERAL(75,0,"SERVIDOR PUBLICO FEDERAL"),
	SERVIDOR_PUBLICO_MUNICIPAL(77,0,"SERVIDOR PUBLICO MUNICIPAL"),
	SOCIOLOGO(27,0,"SOCIOLOGO"),
	SUCATEIRO(216,0,"SUCATEIRO"),
	SUPERVISOR(86,0,"SUPERVISOR, INSPETOR E AGENTE DE COMPRAS E VENDAS"),
	TABELIAO_OFICIAL_DE_REGISTRO(73,0,"TABELIAO/OFICIAL DE REGISTRO"),
	TAPECEIRO(252,0,"TAPECEIRO"),
	TAQUIGRAFO(217,0,"TAQUIGRAFO"),
	TAXISTA(218,0,"TAXISTA"),
	TECNICO_AGRICOLA(39,0,"TECNICO AGRICOLA"),
	TECNICO_DE_BIOLOGIA(38,0,"TECNICO DE BIOLOGIA"),
	TECNICO_DE_CONTABILIDADE_E_DE_ESTATISTICA(37,0,"TECNICO DE CONTABILIDADE E DE ESTATISTICA"),
	TECNICO_DE_EDIFICACOES(299,0,"TECNICO DE EDIFICACOES"),
	TECNICO_DE_ELETRICIDADE(42,0,"TECNICO DE ELETRICIDADE, ELETRONICA E TELECOMUNICACOES"),
	TECNICO_DE_ENFERMAGEM(329,0,"TECNICO DE ENFERMAGEM"),
	TECNICO_DE_INFORMATICA(285,0,"TECNICO DE INFORMATICA"),
	TECNICO_DE_LABORATORIO_E_RAIOS_X(43,0,"TECNICO DE LABORATORIO E RAIOS X"),
	TECNICO_DE_MECANICA(41,0,"TECNICO DE MECANICA"),
	TECNICO_DE_QUIMICA(40,0,"TECNICO DE QUIMICA"),
	TECNICO_EM_AUDIO_E_CENOGRAFIA(51,0,"TECNICO EM AUDIO E CENOGRAFIA"),
	TECNICO_EM_SEGURANCA_DO_TRABALHO(284,0,"TECNICO EM SEGURANCA DO TRABALHO"),
	TECNICO_INSTRUMENTISTA(327,0,"TECNICO INSTRUMENTISTA"),
	TECNOLOGO(8,0,"TECNOLOGO"),
	TINTUREIRO(253,0,"TINTUREIRO"),
	TIPOGRAFO_E_DEMAIS_TRABALHADORES_DE_ARTES_GRAFICAS(131,0,"TIPOGRAFO E DEMAIS TRABALHADORES DE ARTES GRAFICAS"),
	TOPOGRAFO(254,0,"TOPOGRAFO"),
	TORNEIRO_MECANICO(219,0,"TORNEIRO MECANICO"),
	TRAB_DE_SERVICOS_DE_CONTABILIDADE(81,0,"TRAB DE SERVICOS DE CONTABILIDADE, CAIXA E ASSEMELHADOS"),
	TRABALHADOR_DE_CONSTRUCAO_CIVIL(129,0,"TRABALHADOR DE CONSTRUCAO CIVIL"),
	TRABALHADOR_DE_EXTRACAO_DE_MINERIOS(201,0,"TRABALHADOR DE EXTRACAO DE MINERIOS"),
	TRABALHADOR_DE_EXTRACAO_VEGETAL(328,0,"TRABALHADOR DE EXTRACAO VEGETAL"),
	TRABALHADOR_DE_FABRICACAO_DE_PAPEL_E_PAPELAO(134,0,"TRABALHADOR DE FABRICACAO DE PAPEL E PAPELAO"),
	TRABALHADOR_DE_FABRICACAO_DE_PRODUTOS_DE_BORRACHA_E_PLAS(136,0,"TRABALHADOR DE FABRICACAO DE PRODUTOS DE BORRACHA E PLAS"),
	TRABALHADOR_DE_FABRICACAO_DE_ROUPAS(125,0,"TRABALHADOR DE FABRICACAO DE ROUPAS"),
	TRABALHADOR_DE_FABRICACAO_E_PREPARACAO_DE_ALIMENTOS_E_BE(130,0,"TRABALHADOR DE FABRICACAO E PREPARACAO DE ALIMENTOS E BE"),
	TRABALHADOR_DE_INSTALACOES_DE_PROCESSAMENTO_QUIMICO(124,0,"TRABALHADOR DE INSTALACOES DE PROCESSAMENTO QUIMICO"),
	TRABALHADOR_DE_USINAGEM_DE_METAIS(128,0,"TRABALHADOR DE USINAGEM DE METAIS"),
	TRABALHADOR_FLORESTAL(118,0,"TRABALHADOR FLORESTAL"),
	TRABALHADOR_INFORMAL(274,12,"TRABALHADOR INFORMAL"),
	TRABALHADOR_RURAL(288,0,"TRABALHADOR RURAL"),
	TRADUTOR(220,0,"TRADUTOR"),
	VENDEDOR_DE_COMERCIO_VAREJISTA_E_ATACADISTA(91,0,"VENDEDOR DE COMERCIO VAREJISTA E ATACADISTA"),
	VENDEDOR_PRACISTA(87,0,"VENDEDOR PRACISTA, REPRESENT COMERCIAL E CAIXEIRO VIAJAN"),
	VEREADOR(317,13,"VEREADOR"),
	VETERINARIO_OU_ZOOTECNISTA(10,0,"VETERINARIO OU ZOOTECNISTA"),
	VICE_GOVERNADOR_DE_ESTADO_DISTRITO_FEDERAL(325,13,"VICE-GOVERNADOR DE ESTADO/DISTRITO FEDERAL"),
	VICE_PREFEITO_MUNICIPAL(312,13,"VICE-PREFEITO MUNICIPAL"),
	VICE_PRESIDENTE_DA_REPUBLICA(304,13,"VICE-PRESIDENTE DA REPUBLICA"),
	VIDRACEIRO(221,0,"VIDRACEIRO"),
	ZELADOR_DE_EDIFICIO(297,0,"ZELADOR DE EDIFICIO");

	private Integer codigo;
	private Integer natureza;
	private String descricao;

	private OcupacaoValues(Integer codigo, int natureza, String descricao) {
		this.codigo = codigo;
		this.natureza = natureza;
		this.descricao = descricao;
	}

	public static String getDescricaoById(short id) {
		String descricao = null;
		for (OcupacaoValues v : values()) {
			if (v.getCodigo() == id) {
				descricao = v.getDescricao();
				break;
			}
		}
		return descricao;
	}

	public static String getDescricaoById(int id) {
		String descricao = null;
		for (OcupacaoValues v : values()) {
			if (v.getCodigo() == id) {
				descricao = v.getDescricao();
				break;
			}
		}
		return descricao;
	}
	
	public static String getDescricaoById(long id) {
		String descricao = null;
		for (OcupacaoValues v : values()) {
			if (v.getCodigo() == id) {
				descricao = v.getDescricao();
				break;
			}
		}
		return descricao;
	}
	
	public static OcupacaoValues parse(int id){
		OcupacaoValues retorno = null;
		for (OcupacaoValues v: values()){
			if (v.getCodigo() == id) {
				retorno = v;
				break;
			}
		}
		return retorno;
	}

	public Integer getCodigo() {
		return codigo;
	}

	public Integer getNatureza() {
		return natureza;
	}

	public String getDescricao() {
		return descricao;
	}

}
