package br.filipov.values.p;

import static org.junit.Assert.*;

import org.junit.Test;

public class PaisesValuesTest {

	@Test
	public void testGetDescricaoByIdShort() {
		assertEquals("Abecásia",PaisesValues.getDescricaoById((short) 358));
		assertEquals("Afeganistão",PaisesValues.getDescricaoById((short) 4));
		assertEquals("África do Sul",PaisesValues.getDescricaoById((short) 192));
		assertEquals("Albânia",PaisesValues.getDescricaoById((short) 7));
		assertEquals("Alemanha",PaisesValues.getDescricaoById((short) 196));
		assertEquals("Andorra",PaisesValues.getDescricaoById((short) 2));
		assertEquals("Angola",PaisesValues.getDescricaoById((short) 9));
		assertEquals("Anguilla",PaisesValues.getDescricaoById((short) 6));
		assertEquals("Antígua e Barbuda",PaisesValues.getDescricaoById((short) 5));
		assertEquals("Antilhas Holandesas",PaisesValues.getDescricaoById((short) 199));
		assertEquals("Arábia Saudita",PaisesValues.getDescricaoById((short) 155));
		assertEquals("Argélia",PaisesValues.getDescricaoById((short) 49));
		assertEquals("Argentina",PaisesValues.getDescricaoById((short) 10));
		assertEquals("Armênia",PaisesValues.getDescricaoById((short) 8));
		assertEquals("Aruba",PaisesValues.getDescricaoById((short) 200));
		assertEquals("Austrália",PaisesValues.getDescricaoById((short) 12));
		assertEquals("Bahamas",PaisesValues.getDescricaoById((short) 26));
		assertEquals("Bahrein",PaisesValues.getDescricaoById((short) 20));
		assertEquals("Bangladesh",PaisesValues.getDescricaoById((short) 16));
		assertEquals("Barbados",PaisesValues.getDescricaoById((short) 15));
		assertEquals("Bielorrússia",PaisesValues.getDescricaoById((short) 29));
		assertEquals("Bélgica",PaisesValues.getDescricaoById((short) 17));
		assertEquals("Belize",PaisesValues.getDescricaoById((short) 30));
		assertEquals("Benim",PaisesValues.getDescricaoById((short) 22));
		assertEquals("Bermudas",PaisesValues.getDescricaoById((short) 23));
		assertEquals("Bolívia",PaisesValues.getDescricaoById((short) 25));
		assertEquals("Bósnia e Herzegovina",PaisesValues.getDescricaoById((short) 14));
		assertEquals("Botsuana",PaisesValues.getDescricaoById((short) 28));
		assertEquals("Brasil",PaisesValues.getDescricaoById((short) 1));
		assertEquals("Brunei",PaisesValues.getDescricaoById((short) 24));
		assertEquals("Bulgária",PaisesValues.getDescricaoById((short) 19));
		assertEquals("Burkina Faso",PaisesValues.getDescricaoById((short) 18));
		assertEquals("Burundi",PaisesValues.getDescricaoById((short) 21));
		assertEquals("Butão",PaisesValues.getDescricaoById((short) 27));
		assertEquals("Cabo Verde",PaisesValues.getDescricaoById((short) 43));
		assertEquals("Camarões",PaisesValues.getDescricaoById((short) 202));
		assertEquals("Camboja",PaisesValues.getDescricaoById((short) 201));
		assertEquals("Canadá",PaisesValues.getDescricaoById((short) 31));
		assertEquals("Canárias, Ilhas",PaisesValues.getDescricaoById((short) 235));
		assertEquals("Catar",PaisesValues.getDescricaoById((short) 150));
		assertEquals("Cayman, Ilhas",PaisesValues.getDescricaoById((short) 197));
		assertEquals("Cazaquistão",PaisesValues.getDescricaoById((short) 99));
		assertEquals("Chade",PaisesValues.getDescricaoById((short) 170));
		assertEquals("Chile",PaisesValues.getDescricaoById((short) 38));
		assertEquals("China",PaisesValues.getDescricaoById((short) 39));
		assertEquals("Chipre",PaisesValues.getDescricaoById((short) 44));
		assertEquals("Christmas, Ilha",PaisesValues.getDescricaoById((short) 218));
		assertEquals("Cingapura",PaisesValues.getDescricaoById((short) 160));
		assertEquals("Cocos, Ilhas(Keeling)",PaisesValues.getDescricaoById((short) 32));
		assertEquals("Colômbia",PaisesValues.getDescricaoById((short) 40));
		assertEquals("Comores",PaisesValues.getDescricaoById((short) 95));
		assertEquals("Congo",PaisesValues.getDescricaoById((short) 34));
		assertEquals("Cook, Ilhas",PaisesValues.getDescricaoById((short) 37));
		assertEquals("Coréia do Norte",PaisesValues.getDescricaoById((short) 96));
		assertEquals("Coréia do Sul",PaisesValues.getDescricaoById((short) 97));
		assertEquals("Costa do Marfim",PaisesValues.getDescricaoById((short) 36));
		assertEquals("Costa Rica",PaisesValues.getDescricaoById((short) 41));
		assertEquals("Croácia",PaisesValues.getDescricaoById((short) 204));
		assertEquals("Cuba",PaisesValues.getDescricaoById((short) 42));
		assertEquals("Dinamarca",PaisesValues.getDescricaoById((short) 46));
		assertEquals("Djibuti",PaisesValues.getDescricaoById((short) 45));
		assertEquals("Dominica",PaisesValues.getDescricaoById((short) 47));
		assertEquals("Egito",PaisesValues.getDescricaoById((short) 51));
		assertEquals("El Salvador",PaisesValues.getDescricaoById((short) 167));
		assertEquals("Emirados Árabes Unidos",PaisesValues.getDescricaoById((short) 3));
		assertEquals("Equador",PaisesValues.getDescricaoById((short) 50));
		assertEquals("Eritreia",PaisesValues.getDescricaoById((short) 246));
		assertEquals("Eslováquia",PaisesValues.getDescricaoById((short) 206));
		assertEquals("Eslovênia",PaisesValues.getDescricaoById((short) 205));
		assertEquals("Espanha",PaisesValues.getDescricaoById((short) 53));
		assertEquals("Estados Unidos",PaisesValues.getDescricaoById((short) 182));
		assertEquals("Estônia",PaisesValues.getDescricaoById((short) 207));
		assertEquals("Etiópia",PaisesValues.getDescricaoById((short) 54));
		assertEquals("Falkland, Ilhas(Malvinas)",PaisesValues.getDescricaoById((short) 58));
		assertEquals("Feroe, Ilhas",PaisesValues.getDescricaoById((short) 208));
		assertEquals("Fiji",PaisesValues.getDescricaoById((short) 57));
		assertEquals("Filipinas",PaisesValues.getDescricaoById((short) 209));
		assertEquals("Finlândia",PaisesValues.getDescricaoById((short) 56));
		assertEquals("França",PaisesValues.getDescricaoById((short) 60));
		assertEquals("Gabão",PaisesValues.getDescricaoById((short) 61));
		assertEquals("Gâmbia",PaisesValues.getDescricaoById((short) 69));
		assertEquals("Gana",PaisesValues.getDescricaoById((short) 66));
		assertEquals("Georgia",PaisesValues.getDescricaoById((short) 64));
		assertEquals("Gibraltar",PaisesValues.getDescricaoById((short) 67));
		assertEquals("Granada",PaisesValues.getDescricaoById((short) 63));
		assertEquals("Grécia",PaisesValues.getDescricaoById((short) 73));
		assertEquals("Groenlândia",PaisesValues.getDescricaoById((short) 68));
		assertEquals("Guadalupe",PaisesValues.getDescricaoById((short) 71));
		assertEquals("Guam",PaisesValues.getDescricaoById((short) 75));
		assertEquals("Guatemala",PaisesValues.getDescricaoById((short) 74));
		assertEquals("Guernsey, Ilhas do C",PaisesValues.getDescricaoById((short) 65));
		assertEquals("Guiana",PaisesValues.getDescricaoById((short) 76));
		assertEquals("Guiana Francesa",PaisesValues.getDescricaoById((short) 210));
		assertEquals("Guiné",PaisesValues.getDescricaoById((short) 70));
		assertEquals("Guiné Equatorial",PaisesValues.getDescricaoById((short) 72));
		assertEquals("Guiné-Bissau",PaisesValues.getDescricaoById((short) 211));
		assertEquals("Haiti",PaisesValues.getDescricaoById((short) 79));
		assertEquals("Holanda",PaisesValues.getDescricaoById((short) 133));
		assertEquals("Honduras",PaisesValues.getDescricaoById((short) 78));
		assertEquals("Hong Kong",PaisesValues.getDescricaoById((short) 77));
		assertEquals("Hungria",PaisesValues.getDescricaoById((short) 80));
		assertEquals("Iémen",PaisesValues.getDescricaoById((short) 190));
		assertEquals("Índia",PaisesValues.getDescricaoById((short) 84));
		assertEquals("Indonésia",PaisesValues.getDescricaoById((short) 81));
		assertEquals("Irã",PaisesValues.getDescricaoById((short) 212));
		assertEquals("Iraque",PaisesValues.getDescricaoById((short) 86));
		assertEquals("Irlanda",PaisesValues.getDescricaoById((short) 82));
		assertEquals("Islândia",PaisesValues.getDescricaoById((short) 87));
		assertEquals("Israel",PaisesValues.getDescricaoById((short) 83));
		assertEquals("Itália",PaisesValues.getDescricaoById((short) 88));
		assertEquals("Jamaica",PaisesValues.getDescricaoById((short) 90));
		assertEquals("Japão",PaisesValues.getDescricaoById((short) 92));
		assertEquals("Jersey, Ikhas do Can",PaisesValues.getDescricaoById((short) 89));
		assertEquals("Johnston, Ilhas",PaisesValues.getDescricaoById((short) 233));
		assertEquals("Jordânia",PaisesValues.getDescricaoById((short) 91));
		assertEquals("Kiribati",PaisesValues.getDescricaoById((short) 94));
		assertEquals("Kuwait",PaisesValues.getDescricaoById((short) 98));
		assertEquals("Laos",PaisesValues.getDescricaoById((short) 213));
		assertEquals("Lesoto",PaisesValues.getDescricaoById((short) 105));
		assertEquals("Letônia",PaisesValues.getDescricaoById((short) 237));
		assertEquals("Líbano",PaisesValues.getDescricaoById((short) 100));
		assertEquals("Libéria",PaisesValues.getDescricaoById((short) 104));
		assertEquals("Líbia",PaisesValues.getDescricaoById((short) 214));
		assertEquals("Liechtenstein",PaisesValues.getDescricaoById((short) 102));
		assertEquals("Lituânia",PaisesValues.getDescricaoById((short) 106));
		assertEquals("Luxemburgo",PaisesValues.getDescricaoById((short) 107));
		assertEquals("Macau",PaisesValues.getDescricaoById((short) 117));
		assertEquals("Macedônia",PaisesValues.getDescricaoById((short) 113));
		assertEquals("Madagáscar",PaisesValues.getDescricaoById((short) 111));
		assertEquals("Madeira, Ilha",PaisesValues.getDescricaoById((short) 238));
		assertEquals("Malásia",PaisesValues.getDescricaoById((short) 125));
		assertEquals("Malawi",PaisesValues.getDescricaoById((short) 123));
		assertEquals("Maldivas",PaisesValues.getDescricaoById((short) 122));
		assertEquals("Mali",PaisesValues.getDescricaoById((short) 114));
		assertEquals("Malta",PaisesValues.getDescricaoById((short) 120));
		assertEquals("Man, Ilha de",PaisesValues.getDescricaoById((short) 236));
		assertEquals("Marianas do Norte, I",PaisesValues.getDescricaoById((short) 215));
		assertEquals("Marrocos",PaisesValues.getDescricaoById((short) 109));
		assertEquals("Marshall, Ilhas",PaisesValues.getDescricaoById((short) 112));
		assertEquals("Martinica",PaisesValues.getDescricaoById((short) 216));
		assertEquals("Maurício",PaisesValues.getDescricaoById((short) 121));
		assertEquals("Mauritânia",PaisesValues.getDescricaoById((short) 118));
		assertEquals("México",PaisesValues.getDescricaoById((short) 124));
		assertEquals("Mianma",PaisesValues.getDescricaoById((short) 115));
		assertEquals("Micronésia",PaisesValues.getDescricaoById((short) 59));
		assertEquals("Midway, Ilhas",PaisesValues.getDescricaoById((short) 232));
		assertEquals("Moçambique",PaisesValues.getDescricaoById((short) 126));
		assertEquals("Moldávia",PaisesValues.getDescricaoById((short) 217));
		assertEquals("Mônaco",PaisesValues.getDescricaoById((short) 110));
		assertEquals("Mongólia",PaisesValues.getDescricaoById((short) 116));
		assertEquals("MontSerrat",PaisesValues.getDescricaoById((short) 119));
		assertEquals("Namíbia",PaisesValues.getDescricaoById((short) 127));
		assertEquals("Nauru",PaisesValues.getDescricaoById((short) 136));
		assertEquals("Nepal",PaisesValues.getDescricaoById((short) 135));
		assertEquals("Nicaraguá",PaisesValues.getDescricaoById((short) 132));
		assertEquals("Níger",PaisesValues.getDescricaoById((short) 129));
		assertEquals("Nigéria",PaisesValues.getDescricaoById((short) 131));
		assertEquals("Niue",PaisesValues.getDescricaoById((short) 137));
		assertEquals("Norfolk, Ilha",PaisesValues.getDescricaoById((short) 130));
		assertEquals("Noruega",PaisesValues.getDescricaoById((short) 134));
		assertEquals("Nova Caledônia",PaisesValues.getDescricaoById((short) 128));
		assertEquals("Nova Zelândia",PaisesValues.getDescricaoById((short) 138));
		assertEquals("Omã",PaisesValues.getDescricaoById((short) 139));
		assertEquals("Organizações Interna",PaisesValues.getDescricaoById((short) 243));
		assertEquals("Pacífico, Ilhas do",PaisesValues.getDescricaoById((short) 239));
		assertEquals("Palau",PaisesValues.getDescricaoById((short) 147));
		assertEquals("Panamá",PaisesValues.getDescricaoById((short) 140));
		assertEquals("Papua Nova Guiné",PaisesValues.getDescricaoById((short) 219));
		assertEquals("Paquistão",PaisesValues.getDescricaoById((short) 143));
		assertEquals("Paraguai",PaisesValues.getDescricaoById((short) 148));
		assertEquals("Perú",PaisesValues.getDescricaoById((short) 141));
		assertEquals("Pitcairn, Ilha",PaisesValues.getDescricaoById((short) 220));
		assertEquals("Polinésia Francesa",PaisesValues.getDescricaoById((short) 142));
		assertEquals("Polônia",PaisesValues.getDescricaoById((short) 144));
		assertEquals("Porto Rico",PaisesValues.getDescricaoById((short) 145));
		assertEquals("Portugal",PaisesValues.getDescricaoById((short) 146));
		assertEquals("Quênia",PaisesValues.getDescricaoById((short) 93));
		assertEquals("Quirguistão",PaisesValues.getDescricaoById((short) 231));
		assertEquals("Reino Unido",PaisesValues.getDescricaoById((short) 62));
		assertEquals("República Democrática do Congo",PaisesValues.getDescricaoById((short) 194));
		assertEquals("República Centro-Africana",PaisesValues.getDescricaoById((short) 33));
		assertEquals("República Dominicana",PaisesValues.getDescricaoById((short) 48));
		assertEquals("República Tcheca",PaisesValues.getDescricaoById((short) 230));
		assertEquals("Reunião",PaisesValues.getDescricaoById((short) 151));
		assertEquals("Romênia",PaisesValues.getDescricaoById((short) 152));
		assertEquals("Ruanda",PaisesValues.getDescricaoById((short) 154));
		assertEquals("Rússia",PaisesValues.getDescricaoById((short) 153));
		assertEquals("Saara Ocidental",PaisesValues.getDescricaoById((short) 52));
		assertEquals("Salomão, Ilhas",PaisesValues.getDescricaoById((short) 156));
		assertEquals("Samoa",PaisesValues.getDescricaoById((short) 245));
		assertEquals("Samoa Americana",PaisesValues.getDescricaoById((short) 222));
		assertEquals("San Marino",PaisesValues.getDescricaoById((short) 163));
		assertEquals("Santa Helena",PaisesValues.getDescricaoById((short) 161));
		assertEquals("Santa Lúcia",PaisesValues.getDescricaoById((short) 101));
		assertEquals("São Cristovão e Nevi",PaisesValues.getDescricaoById((short) 221));
		assertEquals("São Pedro e Miquelon",PaisesValues.getDescricaoById((short) 223));
		assertEquals("São Tomé e Príncipe",PaisesValues.getDescricaoById((short) 225));
		assertEquals("São Vicente e Granada",PaisesValues.getDescricaoById((short) 224));
		assertEquals("Senegal",PaisesValues.getDescricaoById((short) 164));
		assertEquals("Serra Leoa",PaisesValues.getDescricaoById((short) 162));
		assertEquals("Sérvia e Montenegro",PaisesValues.getDescricaoById((short) 191));
		assertEquals("Seychelles",PaisesValues.getDescricaoById((short) 157));
		assertEquals("Síria",PaisesValues.getDescricaoById((short) 198));
		assertEquals("Somália",PaisesValues.getDescricaoById((short) 165));
		assertEquals("Sri Lanka",PaisesValues.getDescricaoById((short) 103));
		assertEquals("Suazilândia",PaisesValues.getDescricaoById((short) 168));
		assertEquals("Sudão",PaisesValues.getDescricaoById((short) 158));
		assertEquals("Suécia",PaisesValues.getDescricaoById((short) 159));
		assertEquals("Suiça",PaisesValues.getDescricaoById((short) 35));
		assertEquals("Suriname",PaisesValues.getDescricaoById((short) 166));
		assertEquals("Tadjiquistão",PaisesValues.getDescricaoById((short) 226));
		assertEquals("Tailândia",PaisesValues.getDescricaoById((short) 172));
		assertEquals("Taiwan",PaisesValues.getDescricaoById((short) 203));
		assertEquals("Tanzânia",PaisesValues.getDescricaoById((short) 179));
		assertEquals("Território Britânico do Oceano Índico",PaisesValues.getDescricaoById((short) 85));
		assertEquals("Timor Leste",PaisesValues.getDescricaoById((short) 176));
		assertEquals("Togo",PaisesValues.getDescricaoById((short) 171));
		assertEquals("Tonga",PaisesValues.getDescricaoById((short) 175));
		assertEquals("Toquelau, Ilhas",PaisesValues.getDescricaoById((short) 227));
		assertEquals("Trinidad e Tobago",PaisesValues.getDescricaoById((short) 228));
		assertEquals("Tunísia",PaisesValues.getDescricaoById((short) 174));
		assertEquals("Turks e Caicos",PaisesValues.getDescricaoById((short) 169));
		assertEquals("Turcomenistão",PaisesValues.getDescricaoById((short) 173));
		assertEquals("Turquia",PaisesValues.getDescricaoById((short) 177));
		assertEquals("Tuvalu",PaisesValues.getDescricaoById((short) 178));
		assertEquals("Ucrânia",PaisesValues.getDescricaoById((short) 180));
		assertEquals("Uganda",PaisesValues.getDescricaoById((short) 181));
		assertEquals("Uruguai",PaisesValues.getDescricaoById((short) 183));
		assertEquals("Uzbequistão",PaisesValues.getDescricaoById((short) 184));
		assertEquals("Vanuatu",PaisesValues.getDescricaoById((short) 189));
		assertEquals("Vaticano",PaisesValues.getDescricaoById((short) 185));
		assertEquals("Venezuela",PaisesValues.getDescricaoById((short) 186));
		assertEquals("Vietnã",PaisesValues.getDescricaoById((short) 229));
		assertEquals("Virgens, Ilhas",PaisesValues.getDescricaoById((short) 187));
		assertEquals("Virgens, Ilhas (EUA)",PaisesValues.getDescricaoById((short) 188));
		assertEquals("Wake, Ilha",PaisesValues.getDescricaoById((short) 247));
		assertEquals("Zâmbia",PaisesValues.getDescricaoById((short) 193));
		assertEquals("Zimbabwe",PaisesValues.getDescricaoById((short) 195));
		assertEquals("Zona do Canal do Panamá",PaisesValues.getDescricaoById((short) 149));
	}

	
	@Test
	public void testGetDescricaoByIdInteger() {
		assertEquals("Abecásia",PaisesValues.getDescricaoById(358));
		assertEquals("Afeganistão",PaisesValues.getDescricaoById(4));
		assertEquals("África do Sul",PaisesValues.getDescricaoById(192));
		assertEquals("Albânia",PaisesValues.getDescricaoById(7));
		assertEquals("Alemanha",PaisesValues.getDescricaoById(196));
		assertEquals("Andorra",PaisesValues.getDescricaoById(2));
		assertEquals("Angola",PaisesValues.getDescricaoById(9));
		assertEquals("Anguilla",PaisesValues.getDescricaoById(6));
		assertEquals("Antígua e Barbuda",PaisesValues.getDescricaoById(5));
		assertEquals("Antilhas Holandesas",PaisesValues.getDescricaoById(199));
		assertEquals("Arábia Saudita",PaisesValues.getDescricaoById(155));
		assertEquals("Argélia",PaisesValues.getDescricaoById(49));
		assertEquals("Argentina",PaisesValues.getDescricaoById(10));
		assertEquals("Armênia",PaisesValues.getDescricaoById(8));
		assertEquals("Aruba",PaisesValues.getDescricaoById(200));
		assertEquals("Austrália",PaisesValues.getDescricaoById(12));
		assertEquals("Bahamas",PaisesValues.getDescricaoById(26));
		assertEquals("Bahrein",PaisesValues.getDescricaoById(20));
		assertEquals("Bangladesh",PaisesValues.getDescricaoById(16));
		assertEquals("Barbados",PaisesValues.getDescricaoById(15));
		assertEquals("Bielorrússia",PaisesValues.getDescricaoById(29));
		assertEquals("Bélgica",PaisesValues.getDescricaoById(17));
		assertEquals("Belize",PaisesValues.getDescricaoById(30));
		assertEquals("Benim",PaisesValues.getDescricaoById(22));
		assertEquals("Bermudas",PaisesValues.getDescricaoById(23));
		assertEquals("Bolívia",PaisesValues.getDescricaoById(25));
		assertEquals("Bósnia e Herzegovina",PaisesValues.getDescricaoById(14));
		assertEquals("Botsuana",PaisesValues.getDescricaoById(28));
		assertEquals("Brasil",PaisesValues.getDescricaoById(1));
		assertEquals("Brunei",PaisesValues.getDescricaoById(24));
		assertEquals("Bulgária",PaisesValues.getDescricaoById(19));
		assertEquals("Burkina Faso",PaisesValues.getDescricaoById(18));
		assertEquals("Burundi",PaisesValues.getDescricaoById(21));
		assertEquals("Butão",PaisesValues.getDescricaoById(27));
		assertEquals("Cabo Verde",PaisesValues.getDescricaoById(43));
		assertEquals("Camarões",PaisesValues.getDescricaoById(202));
		assertEquals("Camboja",PaisesValues.getDescricaoById(201));
		assertEquals("Canadá",PaisesValues.getDescricaoById(31));
		assertEquals("Canárias, Ilhas",PaisesValues.getDescricaoById(235));
		assertEquals("Catar",PaisesValues.getDescricaoById(150));
		assertEquals("Cayman, Ilhas",PaisesValues.getDescricaoById(197));
		assertEquals("Cazaquistão",PaisesValues.getDescricaoById(99));
		assertEquals("Chade",PaisesValues.getDescricaoById(170));
		assertEquals("Chile",PaisesValues.getDescricaoById(38));
		assertEquals("China",PaisesValues.getDescricaoById(39));
		assertEquals("Chipre",PaisesValues.getDescricaoById(44));
		assertEquals("Christmas, Ilha",PaisesValues.getDescricaoById(218));
		assertEquals("Cingapura",PaisesValues.getDescricaoById(160));
		assertEquals("Cocos, Ilhas(Keeling)",PaisesValues.getDescricaoById(32));
		assertEquals("Colômbia",PaisesValues.getDescricaoById(40));
		assertEquals("Comores",PaisesValues.getDescricaoById(95));
		assertEquals("Congo",PaisesValues.getDescricaoById(34));
		assertEquals("Cook, Ilhas",PaisesValues.getDescricaoById(37));
		assertEquals("Coréia do Norte",PaisesValues.getDescricaoById(96));
		assertEquals("Coréia do Sul",PaisesValues.getDescricaoById(97));
		assertEquals("Costa do Marfim",PaisesValues.getDescricaoById(36));
		assertEquals("Costa Rica",PaisesValues.getDescricaoById(41));
		assertEquals("Croácia",PaisesValues.getDescricaoById(204));
		assertEquals("Cuba",PaisesValues.getDescricaoById(42));
		assertEquals("Dinamarca",PaisesValues.getDescricaoById(46));
		assertEquals("Djibuti",PaisesValues.getDescricaoById(45));
		assertEquals("Dominica",PaisesValues.getDescricaoById(47));
		assertEquals("Egito",PaisesValues.getDescricaoById(51));
		assertEquals("El Salvador",PaisesValues.getDescricaoById(167));
		assertEquals("Emirados Árabes Unidos",PaisesValues.getDescricaoById(3));
		assertEquals("Equador",PaisesValues.getDescricaoById(50));
		assertEquals("Eritreia",PaisesValues.getDescricaoById(246));
		assertEquals("Eslováquia",PaisesValues.getDescricaoById(206));
		assertEquals("Eslovênia",PaisesValues.getDescricaoById(205));
		assertEquals("Espanha",PaisesValues.getDescricaoById(53));
		assertEquals("Estados Unidos",PaisesValues.getDescricaoById(182));
		assertEquals("Estônia",PaisesValues.getDescricaoById(207));
		assertEquals("Etiópia",PaisesValues.getDescricaoById(54));
		assertEquals("Falkland, Ilhas(Malvinas)",PaisesValues.getDescricaoById(58));
		assertEquals("Feroe, Ilhas",PaisesValues.getDescricaoById(208));
		assertEquals("Fiji",PaisesValues.getDescricaoById(57));
		assertEquals("Filipinas",PaisesValues.getDescricaoById(209));
		assertEquals("Finlândia",PaisesValues.getDescricaoById(56));
		assertEquals("França",PaisesValues.getDescricaoById(60));
		assertEquals("Gabão",PaisesValues.getDescricaoById(61));
		assertEquals("Gâmbia",PaisesValues.getDescricaoById(69));
		assertEquals("Gana",PaisesValues.getDescricaoById(66));
		assertEquals("Georgia",PaisesValues.getDescricaoById(64));
		assertEquals("Gibraltar",PaisesValues.getDescricaoById(67));
		assertEquals("Granada",PaisesValues.getDescricaoById(63));
		assertEquals("Grécia",PaisesValues.getDescricaoById(73));
		assertEquals("Groenlândia",PaisesValues.getDescricaoById(68));
		assertEquals("Guadalupe",PaisesValues.getDescricaoById(71));
		assertEquals("Guam",PaisesValues.getDescricaoById(75));
		assertEquals("Guatemala",PaisesValues.getDescricaoById(74));
		assertEquals("Guernsey, Ilhas do C",PaisesValues.getDescricaoById(65));
		assertEquals("Guiana",PaisesValues.getDescricaoById(76));
		assertEquals("Guiana Francesa",PaisesValues.getDescricaoById(210));
		assertEquals("Guiné",PaisesValues.getDescricaoById(70));
		assertEquals("Guiné Equatorial",PaisesValues.getDescricaoById(72));
		assertEquals("Guiné-Bissau",PaisesValues.getDescricaoById(211));
		assertEquals("Haiti",PaisesValues.getDescricaoById(79));
		assertEquals("Holanda",PaisesValues.getDescricaoById(133));
		assertEquals("Honduras",PaisesValues.getDescricaoById(78));
		assertEquals("Hong Kong",PaisesValues.getDescricaoById(77));
		assertEquals("Hungria",PaisesValues.getDescricaoById(80));
		assertEquals("Iémen",PaisesValues.getDescricaoById(190));
		assertEquals("Índia",PaisesValues.getDescricaoById(84));
		assertEquals("Indonésia",PaisesValues.getDescricaoById(81));
		assertEquals("Irã",PaisesValues.getDescricaoById(212));
		assertEquals("Iraque",PaisesValues.getDescricaoById(86));
		assertEquals("Irlanda",PaisesValues.getDescricaoById(82));
		assertEquals("Islândia",PaisesValues.getDescricaoById(87));
		assertEquals("Israel",PaisesValues.getDescricaoById(83));
		assertEquals("Itália",PaisesValues.getDescricaoById(88));
		assertEquals("Jamaica",PaisesValues.getDescricaoById(90));
		assertEquals("Japão",PaisesValues.getDescricaoById(92));
		assertEquals("Jersey, Ikhas do Can",PaisesValues.getDescricaoById(89));
		assertEquals("Johnston, Ilhas",PaisesValues.getDescricaoById(233));
		assertEquals("Jordânia",PaisesValues.getDescricaoById(91));
		assertEquals("Kiribati",PaisesValues.getDescricaoById(94));
		assertEquals("Kuwait",PaisesValues.getDescricaoById(98));
		assertEquals("Laos",PaisesValues.getDescricaoById(213));
		assertEquals("Lesoto",PaisesValues.getDescricaoById(105));
		assertEquals("Letônia",PaisesValues.getDescricaoById(237));
		assertEquals("Líbano",PaisesValues.getDescricaoById(100));
		assertEquals("Libéria",PaisesValues.getDescricaoById(104));
		assertEquals("Líbia",PaisesValues.getDescricaoById(214));
		assertEquals("Liechtenstein",PaisesValues.getDescricaoById(102));
		assertEquals("Lituânia",PaisesValues.getDescricaoById(106));
		assertEquals("Luxemburgo",PaisesValues.getDescricaoById(107));
		assertEquals("Macau",PaisesValues.getDescricaoById(117));
		assertEquals("Macedônia",PaisesValues.getDescricaoById(113));
		assertEquals("Madagáscar",PaisesValues.getDescricaoById(111));
		assertEquals("Madeira, Ilha",PaisesValues.getDescricaoById(238));
		assertEquals("Malásia",PaisesValues.getDescricaoById(125));
		assertEquals("Malawi",PaisesValues.getDescricaoById(123));
		assertEquals("Maldivas",PaisesValues.getDescricaoById(122));
		assertEquals("Mali",PaisesValues.getDescricaoById(114));
		assertEquals("Malta",PaisesValues.getDescricaoById(120));
		assertEquals("Man, Ilha de",PaisesValues.getDescricaoById(236));
		assertEquals("Marianas do Norte, I",PaisesValues.getDescricaoById(215));
		assertEquals("Marrocos",PaisesValues.getDescricaoById(109));
		assertEquals("Marshall, Ilhas",PaisesValues.getDescricaoById(112));
		assertEquals("Martinica",PaisesValues.getDescricaoById(216));
		assertEquals("Maurício",PaisesValues.getDescricaoById(121));
		assertEquals("Mauritânia",PaisesValues.getDescricaoById(118));
		assertEquals("México",PaisesValues.getDescricaoById(124));
		assertEquals("Mianma",PaisesValues.getDescricaoById(115));
		assertEquals("Micronésia",PaisesValues.getDescricaoById(59));
		assertEquals("Midway, Ilhas",PaisesValues.getDescricaoById(232));
		assertEquals("Moçambique",PaisesValues.getDescricaoById(126));
		assertEquals("Moldávia",PaisesValues.getDescricaoById(217));
		assertEquals("Mônaco",PaisesValues.getDescricaoById(110));
		assertEquals("Mongólia",PaisesValues.getDescricaoById(116));
		assertEquals("MontSerrat",PaisesValues.getDescricaoById(119));
		assertEquals("Namíbia",PaisesValues.getDescricaoById(127));
		assertEquals("Nauru",PaisesValues.getDescricaoById(136));
		assertEquals("Nepal",PaisesValues.getDescricaoById(135));
		assertEquals("Nicaraguá",PaisesValues.getDescricaoById(132));
		assertEquals("Níger",PaisesValues.getDescricaoById(129));
		assertEquals("Nigéria",PaisesValues.getDescricaoById(131));
		assertEquals("Niue",PaisesValues.getDescricaoById(137));
		assertEquals("Norfolk, Ilha",PaisesValues.getDescricaoById(130));
		assertEquals("Noruega",PaisesValues.getDescricaoById(134));
		assertEquals("Nova Caledônia",PaisesValues.getDescricaoById(128));
		assertEquals("Nova Zelândia",PaisesValues.getDescricaoById(138));
		assertEquals("Omã",PaisesValues.getDescricaoById(139));
		assertEquals("Organizações Interna",PaisesValues.getDescricaoById(243));
		assertEquals("Pacífico, Ilhas do",PaisesValues.getDescricaoById(239));
		assertEquals("Palau",PaisesValues.getDescricaoById(147));
		assertEquals("Panamá",PaisesValues.getDescricaoById(140));
		assertEquals("Papua Nova Guiné",PaisesValues.getDescricaoById(219));
		assertEquals("Paquistão",PaisesValues.getDescricaoById(143));
		assertEquals("Paraguai",PaisesValues.getDescricaoById(148));
		assertEquals("Perú",PaisesValues.getDescricaoById(141));
		assertEquals("Pitcairn, Ilha",PaisesValues.getDescricaoById(220));
		assertEquals("Polinésia Francesa",PaisesValues.getDescricaoById(142));
		assertEquals("Polônia",PaisesValues.getDescricaoById(144));
		assertEquals("Porto Rico",PaisesValues.getDescricaoById(145));
		assertEquals("Portugal",PaisesValues.getDescricaoById(146));
		assertEquals("Quênia",PaisesValues.getDescricaoById(93));
		assertEquals("Quirguistão",PaisesValues.getDescricaoById(231));
		assertEquals("Reino Unido",PaisesValues.getDescricaoById(62));
		assertEquals("República Democrática do Congo",PaisesValues.getDescricaoById(194));
		assertEquals("República Centro-Africana",PaisesValues.getDescricaoById(33));
		assertEquals("República Dominicana",PaisesValues.getDescricaoById(48));
		assertEquals("República Tcheca",PaisesValues.getDescricaoById(230));
		assertEquals("Reunião",PaisesValues.getDescricaoById(151));
		assertEquals("Romênia",PaisesValues.getDescricaoById(152));
		assertEquals("Ruanda",PaisesValues.getDescricaoById(154));
		assertEquals("Rússia",PaisesValues.getDescricaoById(153));
		assertEquals("Saara Ocidental",PaisesValues.getDescricaoById(52));
		assertEquals("Salomão, Ilhas",PaisesValues.getDescricaoById(156));
		assertEquals("Samoa",PaisesValues.getDescricaoById(245));
		assertEquals("Samoa Americana",PaisesValues.getDescricaoById(222));
		assertEquals("San Marino",PaisesValues.getDescricaoById(163));
		assertEquals("Santa Helena",PaisesValues.getDescricaoById(161));
		assertEquals("Santa Lúcia",PaisesValues.getDescricaoById(101));
		assertEquals("São Cristovão e Nevi",PaisesValues.getDescricaoById(221));
		assertEquals("São Pedro e Miquelon",PaisesValues.getDescricaoById(223));
		assertEquals("São Tomé e Príncipe",PaisesValues.getDescricaoById(225));
		assertEquals("São Vicente e Granada",PaisesValues.getDescricaoById(224));
		assertEquals("Senegal",PaisesValues.getDescricaoById(164));
		assertEquals("Serra Leoa",PaisesValues.getDescricaoById(162));
		assertEquals("Sérvia e Montenegro",PaisesValues.getDescricaoById(191));
		assertEquals("Seychelles",PaisesValues.getDescricaoById(157));
		assertEquals("Síria",PaisesValues.getDescricaoById(198));
		assertEquals("Somália",PaisesValues.getDescricaoById(165));
		assertEquals("Sri Lanka",PaisesValues.getDescricaoById(103));
		assertEquals("Suazilândia",PaisesValues.getDescricaoById(168));
		assertEquals("Sudão",PaisesValues.getDescricaoById(158));
		assertEquals("Suécia",PaisesValues.getDescricaoById(159));
		assertEquals("Suiça",PaisesValues.getDescricaoById(35));
		assertEquals("Suriname",PaisesValues.getDescricaoById(166));
		assertEquals("Tadjiquistão",PaisesValues.getDescricaoById(226));
		assertEquals("Tailândia",PaisesValues.getDescricaoById(172));
		assertEquals("Taiwan",PaisesValues.getDescricaoById(203));
		assertEquals("Tanzânia",PaisesValues.getDescricaoById(179));
		assertEquals("Território Britânico do Oceano Índico",PaisesValues.getDescricaoById(85));
		assertEquals("Timor Leste",PaisesValues.getDescricaoById(176));
		assertEquals("Togo",PaisesValues.getDescricaoById(171));
		assertEquals("Tonga",PaisesValues.getDescricaoById(175));
		assertEquals("Toquelau, Ilhas",PaisesValues.getDescricaoById(227));
		assertEquals("Trinidad e Tobago",PaisesValues.getDescricaoById(228));
		assertEquals("Tunísia",PaisesValues.getDescricaoById(174));
		assertEquals("Turks e Caicos",PaisesValues.getDescricaoById(169));
		assertEquals("Turcomenistão",PaisesValues.getDescricaoById(173));
		assertEquals("Turquia",PaisesValues.getDescricaoById(177));
		assertEquals("Tuvalu",PaisesValues.getDescricaoById(178));
		assertEquals("Ucrânia",PaisesValues.getDescricaoById(180));
		assertEquals("Uganda",PaisesValues.getDescricaoById(181));
		assertEquals("Uruguai",PaisesValues.getDescricaoById(183));
		assertEquals("Uzbequistão",PaisesValues.getDescricaoById(184));
		assertEquals("Vanuatu",PaisesValues.getDescricaoById(189));
		assertEquals("Vaticano",PaisesValues.getDescricaoById(185));
		assertEquals("Venezuela",PaisesValues.getDescricaoById(186));
		assertEquals("Vietnã",PaisesValues.getDescricaoById(229));
		assertEquals("Virgens, Ilhas",PaisesValues.getDescricaoById(187));
		assertEquals("Virgens, Ilhas (EUA)",PaisesValues.getDescricaoById(188));
		assertEquals("Wake, Ilha",PaisesValues.getDescricaoById(247));
		assertEquals("Zâmbia",PaisesValues.getDescricaoById(193));
		assertEquals("Zimbabwe",PaisesValues.getDescricaoById(195));
		assertEquals("Zona do Canal do Panamá",PaisesValues.getDescricaoById(149));
	}

	@Test
	public void testGetDescricaoByIdLong() {
		assertEquals("Abecásia",PaisesValues.getDescricaoById(358L));
		assertEquals("Afeganistão",PaisesValues.getDescricaoById(4L));
		assertEquals("África do Sul",PaisesValues.getDescricaoById(192L));
		assertEquals("Albânia",PaisesValues.getDescricaoById(7L));
		assertEquals("Alemanha",PaisesValues.getDescricaoById(196L));
		assertEquals("Andorra",PaisesValues.getDescricaoById(2L));
		assertEquals("Angola",PaisesValues.getDescricaoById(9L));
		assertEquals("Anguilla",PaisesValues.getDescricaoById(6L));
		assertEquals("Antígua e Barbuda",PaisesValues.getDescricaoById(5L));
		assertEquals("Antilhas Holandesas",PaisesValues.getDescricaoById(199L));
		assertEquals("Arábia Saudita",PaisesValues.getDescricaoById(155L));
		assertEquals("Argélia",PaisesValues.getDescricaoById(49L));
		assertEquals("Argentina",PaisesValues.getDescricaoById(10L));
		assertEquals("Armênia",PaisesValues.getDescricaoById(8L));
		assertEquals("Aruba",PaisesValues.getDescricaoById(200L));
		assertEquals("Austrália",PaisesValues.getDescricaoById(12L));
		assertEquals("Bahamas",PaisesValues.getDescricaoById(26L));
		assertEquals("Bahrein",PaisesValues.getDescricaoById(20L));
		assertEquals("Bangladesh",PaisesValues.getDescricaoById(16L));
		assertEquals("Barbados",PaisesValues.getDescricaoById(15L));
		assertEquals("Bielorrússia",PaisesValues.getDescricaoById(29L));
		assertEquals("Bélgica",PaisesValues.getDescricaoById(17L));
		assertEquals("Belize",PaisesValues.getDescricaoById(30L));
		assertEquals("Benim",PaisesValues.getDescricaoById(22L));
		assertEquals("Bermudas",PaisesValues.getDescricaoById(23L));
		assertEquals("Bolívia",PaisesValues.getDescricaoById(25L));
		assertEquals("Bósnia e Herzegovina",PaisesValues.getDescricaoById(14L));
		assertEquals("Botsuana",PaisesValues.getDescricaoById(28L));
		assertEquals("Brasil",PaisesValues.getDescricaoById(1L));
		assertEquals("Brunei",PaisesValues.getDescricaoById(24L));
		assertEquals("Bulgária",PaisesValues.getDescricaoById(19L));
		assertEquals("Burkina Faso",PaisesValues.getDescricaoById(18L));
		assertEquals("Burundi",PaisesValues.getDescricaoById(21L));
		assertEquals("Butão",PaisesValues.getDescricaoById(27L));
		assertEquals("Cabo Verde",PaisesValues.getDescricaoById(43L));
		assertEquals("Camarões",PaisesValues.getDescricaoById(202L));
		assertEquals("Camboja",PaisesValues.getDescricaoById(201L));
		assertEquals("Canadá",PaisesValues.getDescricaoById(31L));
		assertEquals("Canárias, Ilhas",PaisesValues.getDescricaoById(235L));
		assertEquals("Catar",PaisesValues.getDescricaoById(150L));
		assertEquals("Cayman, Ilhas",PaisesValues.getDescricaoById(197L));
		assertEquals("Cazaquistão",PaisesValues.getDescricaoById(99L));
		assertEquals("Chade",PaisesValues.getDescricaoById(170L));
		assertEquals("Chile",PaisesValues.getDescricaoById(38L));
		assertEquals("China",PaisesValues.getDescricaoById(39L));
		assertEquals("Chipre",PaisesValues.getDescricaoById(44L));
		assertEquals("Christmas, Ilha",PaisesValues.getDescricaoById(218L));
		assertEquals("Cingapura",PaisesValues.getDescricaoById(160L));
		assertEquals("Cocos, Ilhas(Keeling)",PaisesValues.getDescricaoById(32L));
		assertEquals("Colômbia",PaisesValues.getDescricaoById(40L));
		assertEquals("Comores",PaisesValues.getDescricaoById(95L));
		assertEquals("Congo",PaisesValues.getDescricaoById(34L));
		assertEquals("Cook, Ilhas",PaisesValues.getDescricaoById(37L));
		assertEquals("Coréia do Norte",PaisesValues.getDescricaoById(96L));
		assertEquals("Coréia do Sul",PaisesValues.getDescricaoById(97L));
		assertEquals("Costa do Marfim",PaisesValues.getDescricaoById(36L));
		assertEquals("Costa Rica",PaisesValues.getDescricaoById(41L));
		assertEquals("Croácia",PaisesValues.getDescricaoById(204L));
		assertEquals("Cuba",PaisesValues.getDescricaoById(42L));
		assertEquals("Dinamarca",PaisesValues.getDescricaoById(46L));
		assertEquals("Djibuti",PaisesValues.getDescricaoById(45L));
		assertEquals("Dominica",PaisesValues.getDescricaoById(47L));
		assertEquals("Egito",PaisesValues.getDescricaoById(51L));
		assertEquals("El Salvador",PaisesValues.getDescricaoById(167L));
		assertEquals("Emirados Árabes Unidos",PaisesValues.getDescricaoById(3L));
		assertEquals("Equador",PaisesValues.getDescricaoById(50L));
		assertEquals("Eritreia",PaisesValues.getDescricaoById(246L));
		assertEquals("Eslováquia",PaisesValues.getDescricaoById(206L));
		assertEquals("Eslovênia",PaisesValues.getDescricaoById(205L));
		assertEquals("Espanha",PaisesValues.getDescricaoById(53L));
		assertEquals("Estados Unidos",PaisesValues.getDescricaoById(182L));
		assertEquals("Estônia",PaisesValues.getDescricaoById(207L));
		assertEquals("Etiópia",PaisesValues.getDescricaoById(54L));
		assertEquals("Falkland, Ilhas(Malvinas)",PaisesValues.getDescricaoById(58L));
		assertEquals("Feroe, Ilhas",PaisesValues.getDescricaoById(208L));
		assertEquals("Fiji",PaisesValues.getDescricaoById(57L));
		assertEquals("Filipinas",PaisesValues.getDescricaoById(209L));
		assertEquals("Finlândia",PaisesValues.getDescricaoById(56L));
		assertEquals("França",PaisesValues.getDescricaoById(60L));
		assertEquals("Gabão",PaisesValues.getDescricaoById(61L));
		assertEquals("Gâmbia",PaisesValues.getDescricaoById(69L));
		assertEquals("Gana",PaisesValues.getDescricaoById(66L));
		assertEquals("Georgia",PaisesValues.getDescricaoById(64L));
		assertEquals("Gibraltar",PaisesValues.getDescricaoById(67L));
		assertEquals("Granada",PaisesValues.getDescricaoById(63L));
		assertEquals("Grécia",PaisesValues.getDescricaoById(73L));
		assertEquals("Groenlândia",PaisesValues.getDescricaoById(68L));
		assertEquals("Guadalupe",PaisesValues.getDescricaoById(71L));
		assertEquals("Guam",PaisesValues.getDescricaoById(75L));
		assertEquals("Guatemala",PaisesValues.getDescricaoById(74L));
		assertEquals("Guernsey, Ilhas do C",PaisesValues.getDescricaoById(65L));
		assertEquals("Guiana",PaisesValues.getDescricaoById(76L));
		assertEquals("Guiana Francesa",PaisesValues.getDescricaoById(210L));
		assertEquals("Guiné",PaisesValues.getDescricaoById(70L));
		assertEquals("Guiné Equatorial",PaisesValues.getDescricaoById(72L));
		assertEquals("Guiné-Bissau",PaisesValues.getDescricaoById(211L));
		assertEquals("Haiti",PaisesValues.getDescricaoById(79L));
		assertEquals("Holanda",PaisesValues.getDescricaoById(133L));
		assertEquals("Honduras",PaisesValues.getDescricaoById(78L));
		assertEquals("Hong Kong",PaisesValues.getDescricaoById(77L));
		assertEquals("Hungria",PaisesValues.getDescricaoById(80L));
		assertEquals("Iémen",PaisesValues.getDescricaoById(190L));
		assertEquals("Índia",PaisesValues.getDescricaoById(84L));
		assertEquals("Indonésia",PaisesValues.getDescricaoById(81L));
		assertEquals("Irã",PaisesValues.getDescricaoById(212L));
		assertEquals("Iraque",PaisesValues.getDescricaoById(86L));
		assertEquals("Irlanda",PaisesValues.getDescricaoById(82L));
		assertEquals("Islândia",PaisesValues.getDescricaoById(87L));
		assertEquals("Israel",PaisesValues.getDescricaoById(83L));
		assertEquals("Itália",PaisesValues.getDescricaoById(88L));
		assertEquals("Jamaica",PaisesValues.getDescricaoById(90L));
		assertEquals("Japão",PaisesValues.getDescricaoById(92L));
		assertEquals("Jersey, Ikhas do Can",PaisesValues.getDescricaoById(89L));
		assertEquals("Johnston, Ilhas",PaisesValues.getDescricaoById(233L));
		assertEquals("Jordânia",PaisesValues.getDescricaoById(91L));
		assertEquals("Kiribati",PaisesValues.getDescricaoById(94L));
		assertEquals("Kuwait",PaisesValues.getDescricaoById(98L));
		assertEquals("Laos",PaisesValues.getDescricaoById(213L));
		assertEquals("Lesoto",PaisesValues.getDescricaoById(105L));
		assertEquals("Letônia",PaisesValues.getDescricaoById(237L));
		assertEquals("Líbano",PaisesValues.getDescricaoById(100L));
		assertEquals("Libéria",PaisesValues.getDescricaoById(104L));
		assertEquals("Líbia",PaisesValues.getDescricaoById(214L));
		assertEquals("Liechtenstein",PaisesValues.getDescricaoById(102L));
		assertEquals("Lituânia",PaisesValues.getDescricaoById(106L));
		assertEquals("Luxemburgo",PaisesValues.getDescricaoById(107L));
		assertEquals("Macau",PaisesValues.getDescricaoById(117L));
		assertEquals("Macedônia",PaisesValues.getDescricaoById(113L));
		assertEquals("Madagáscar",PaisesValues.getDescricaoById(111L));
		assertEquals("Madeira, Ilha",PaisesValues.getDescricaoById(238L));
		assertEquals("Malásia",PaisesValues.getDescricaoById(125L));
		assertEquals("Malawi",PaisesValues.getDescricaoById(123L));
		assertEquals("Maldivas",PaisesValues.getDescricaoById(122L));
		assertEquals("Mali",PaisesValues.getDescricaoById(114L));
		assertEquals("Malta",PaisesValues.getDescricaoById(120L));
		assertEquals("Man, Ilha de",PaisesValues.getDescricaoById(236L));
		assertEquals("Marianas do Norte, I",PaisesValues.getDescricaoById(215L));
		assertEquals("Marrocos",PaisesValues.getDescricaoById(109L));
		assertEquals("Marshall, Ilhas",PaisesValues.getDescricaoById(112L));
		assertEquals("Martinica",PaisesValues.getDescricaoById(216L));
		assertEquals("Maurício",PaisesValues.getDescricaoById(121L));
		assertEquals("Mauritânia",PaisesValues.getDescricaoById(118L));
		assertEquals("México",PaisesValues.getDescricaoById(124L));
		assertEquals("Mianma",PaisesValues.getDescricaoById(115L));
		assertEquals("Micronésia",PaisesValues.getDescricaoById(59L));
		assertEquals("Midway, Ilhas",PaisesValues.getDescricaoById(232L));
		assertEquals("Moçambique",PaisesValues.getDescricaoById(126L));
		assertEquals("Moldávia",PaisesValues.getDescricaoById(217L));
		assertEquals("Mônaco",PaisesValues.getDescricaoById(110L));
		assertEquals("Mongólia",PaisesValues.getDescricaoById(116L));
		assertEquals("MontSerrat",PaisesValues.getDescricaoById(119L));
		assertEquals("Namíbia",PaisesValues.getDescricaoById(127L));
		assertEquals("Nauru",PaisesValues.getDescricaoById(136L));
		assertEquals("Nepal",PaisesValues.getDescricaoById(135L));
		assertEquals("Nicaraguá",PaisesValues.getDescricaoById(132L));
		assertEquals("Níger",PaisesValues.getDescricaoById(129L));
		assertEquals("Nigéria",PaisesValues.getDescricaoById(131L));
		assertEquals("Niue",PaisesValues.getDescricaoById(137L));
		assertEquals("Norfolk, Ilha",PaisesValues.getDescricaoById(130L));
		assertEquals("Noruega",PaisesValues.getDescricaoById(134L));
		assertEquals("Nova Caledônia",PaisesValues.getDescricaoById(128L));
		assertEquals("Nova Zelândia",PaisesValues.getDescricaoById(138L));
		assertEquals("Omã",PaisesValues.getDescricaoById(139L));
		assertEquals("Organizações Interna",PaisesValues.getDescricaoById(243L));
		assertEquals("Pacífico, Ilhas do",PaisesValues.getDescricaoById(239L));
		assertEquals("Palau",PaisesValues.getDescricaoById(147L));
		assertEquals("Panamá",PaisesValues.getDescricaoById(140L));
		assertEquals("Papua Nova Guiné",PaisesValues.getDescricaoById(219L));
		assertEquals("Paquistão",PaisesValues.getDescricaoById(143L));
		assertEquals("Paraguai",PaisesValues.getDescricaoById(148L));
		assertEquals("Perú",PaisesValues.getDescricaoById(141L));
		assertEquals("Pitcairn, Ilha",PaisesValues.getDescricaoById(220L));
		assertEquals("Polinésia Francesa",PaisesValues.getDescricaoById(142L));
		assertEquals("Polônia",PaisesValues.getDescricaoById(144L));
		assertEquals("Porto Rico",PaisesValues.getDescricaoById(145L));
		assertEquals("Portugal",PaisesValues.getDescricaoById(146L));
		assertEquals("Quênia",PaisesValues.getDescricaoById(93L));
		assertEquals("Quirguistão",PaisesValues.getDescricaoById(231L));
		assertEquals("Reino Unido",PaisesValues.getDescricaoById(62L));
		assertEquals("República Democrática do Congo",PaisesValues.getDescricaoById(194L));
		assertEquals("República Centro-Africana",PaisesValues.getDescricaoById(33L));
		assertEquals("República Dominicana",PaisesValues.getDescricaoById(48L));
		assertEquals("República Tcheca",PaisesValues.getDescricaoById(230L));
		assertEquals("Reunião",PaisesValues.getDescricaoById(151L));
		assertEquals("Romênia",PaisesValues.getDescricaoById(152L));
		assertEquals("Ruanda",PaisesValues.getDescricaoById(154L));
		assertEquals("Rússia",PaisesValues.getDescricaoById(153L));
		assertEquals("Saara Ocidental",PaisesValues.getDescricaoById(52L));
		assertEquals("Salomão, Ilhas",PaisesValues.getDescricaoById(156L));
		assertEquals("Samoa",PaisesValues.getDescricaoById(245L));
		assertEquals("Samoa Americana",PaisesValues.getDescricaoById(222L));
		assertEquals("San Marino",PaisesValues.getDescricaoById(163L));
		assertEquals("Santa Helena",PaisesValues.getDescricaoById(161L));
		assertEquals("Santa Lúcia",PaisesValues.getDescricaoById(101L));
		assertEquals("São Cristovão e Nevi",PaisesValues.getDescricaoById(221L));
		assertEquals("São Pedro e Miquelon",PaisesValues.getDescricaoById(223L));
		assertEquals("São Tomé e Príncipe",PaisesValues.getDescricaoById(225L));
		assertEquals("São Vicente e Granada",PaisesValues.getDescricaoById(224L));
		assertEquals("Senegal",PaisesValues.getDescricaoById(164L));
		assertEquals("Serra Leoa",PaisesValues.getDescricaoById(162L));
		assertEquals("Sérvia e Montenegro",PaisesValues.getDescricaoById(191L));
		assertEquals("Seychelles",PaisesValues.getDescricaoById(157L));
		assertEquals("Síria",PaisesValues.getDescricaoById(198L));
		assertEquals("Somália",PaisesValues.getDescricaoById(165L));
		assertEquals("Sri Lanka",PaisesValues.getDescricaoById(103L));
		assertEquals("Suazilândia",PaisesValues.getDescricaoById(168L));
		assertEquals("Sudão",PaisesValues.getDescricaoById(158L));
		assertEquals("Suécia",PaisesValues.getDescricaoById(159L));
		assertEquals("Suiça",PaisesValues.getDescricaoById(35L));
		assertEquals("Suriname",PaisesValues.getDescricaoById(166L));
		assertEquals("Tadjiquistão",PaisesValues.getDescricaoById(226L));
		assertEquals("Tailândia",PaisesValues.getDescricaoById(172L));
		assertEquals("Taiwan",PaisesValues.getDescricaoById(203L));
		assertEquals("Tanzânia",PaisesValues.getDescricaoById(179L));
		assertEquals("Território Britânico do Oceano Índico",PaisesValues.getDescricaoById(85L));
		assertEquals("Timor Leste",PaisesValues.getDescricaoById(176L));
		assertEquals("Togo",PaisesValues.getDescricaoById(171L));
		assertEquals("Tonga",PaisesValues.getDescricaoById(175L));
		assertEquals("Toquelau, Ilhas",PaisesValues.getDescricaoById(227L));
		assertEquals("Trinidad e Tobago",PaisesValues.getDescricaoById(228L));
		assertEquals("Tunísia",PaisesValues.getDescricaoById(174L));
		assertEquals("Turks e Caicos",PaisesValues.getDescricaoById(169L));
		assertEquals("Turcomenistão",PaisesValues.getDescricaoById(173L));
		assertEquals("Turquia",PaisesValues.getDescricaoById(177L));
		assertEquals("Tuvalu",PaisesValues.getDescricaoById(178L));
		assertEquals("Ucrânia",PaisesValues.getDescricaoById(180L));
		assertEquals("Uganda",PaisesValues.getDescricaoById(181L));
		assertEquals("Uruguai",PaisesValues.getDescricaoById(183L));
		assertEquals("Uzbequistão",PaisesValues.getDescricaoById(184L));
		assertEquals("Vanuatu",PaisesValues.getDescricaoById(189L));
		assertEquals("Vaticano",PaisesValues.getDescricaoById(185L));
		assertEquals("Venezuela",PaisesValues.getDescricaoById(186L));
		assertEquals("Vietnã",PaisesValues.getDescricaoById(229L));
		assertEquals("Virgens, Ilhas",PaisesValues.getDescricaoById(187L));
		assertEquals("Virgens, Ilhas (EUA)",PaisesValues.getDescricaoById(188L));
		assertEquals("Wake, Ilha",PaisesValues.getDescricaoById(247L));
		assertEquals("Zâmbia",PaisesValues.getDescricaoById(193L));
		assertEquals("Zimbabwe",PaisesValues.getDescricaoById(195L));
		assertEquals("Zona do Canal do Panamá",PaisesValues.getDescricaoById(149L));
	}	
	
	@Test
	public void testParse() {
		assertEquals(PaisesValues.ABECASIA,PaisesValues.parse(358));
		assertEquals(PaisesValues.AFEGANISTAO,PaisesValues.parse(4));
		assertEquals(PaisesValues.AFRICA_DO_SUL,PaisesValues.parse(192));
		assertEquals(PaisesValues.ALBANIA,PaisesValues.parse(7));
		assertEquals(PaisesValues.ALEMANHA,PaisesValues.parse(196));
		assertEquals(PaisesValues.ANDORRA,PaisesValues.parse(2));
		assertEquals(PaisesValues.ANGOLA,PaisesValues.parse(9));
		assertEquals(PaisesValues.ANGUILLA,PaisesValues.parse(6));
		assertEquals(PaisesValues.ANTIGUA_E_BARBUDA,PaisesValues.parse(5));
		assertEquals(PaisesValues.ANTILHAS_HOLANDESAS,PaisesValues.parse(199));
		assertEquals(PaisesValues.ARABIA_SAUDITA,PaisesValues.parse(155));
		assertEquals(PaisesValues.ARGELIA,PaisesValues.parse(49));
		assertEquals(PaisesValues.ARGENTINA,PaisesValues.parse(10));
		assertEquals(PaisesValues.ARMENIA,PaisesValues.parse(8));
		assertEquals(PaisesValues.ARUBA,PaisesValues.parse(200));
		assertEquals(PaisesValues.AUSTRALIA,PaisesValues.parse(12));
		assertEquals(PaisesValues.BAHAMAS,PaisesValues.parse(26));
		assertEquals(PaisesValues.BAHREIN,PaisesValues.parse(20));
		assertEquals(PaisesValues.BANGLADESH,PaisesValues.parse(16));
		assertEquals(PaisesValues.BARBADOS,PaisesValues.parse(15));
		assertEquals(PaisesValues.BELARUS,PaisesValues.parse(29));
		assertEquals(PaisesValues.BELGICA,PaisesValues.parse(17));
		assertEquals(PaisesValues.BELIZE,PaisesValues.parse(30));
		assertEquals(PaisesValues.BENIM,PaisesValues.parse(22));
		assertEquals(PaisesValues.BERMUDAS,PaisesValues.parse(23));
		assertEquals(PaisesValues.BOLIVIA,PaisesValues.parse(25));
		assertEquals(PaisesValues.BOSNIA_HERZEGOVINA,PaisesValues.parse(14));
		assertEquals(PaisesValues.BOTSUANA,PaisesValues.parse(28));
		assertEquals(PaisesValues.BRASIL,PaisesValues.parse(1));
		assertEquals(PaisesValues.BRUNEI,PaisesValues.parse(24));
		assertEquals(PaisesValues.BULGARIA,PaisesValues.parse(19));
		assertEquals(PaisesValues.BURKINA_FASO,PaisesValues.parse(18));
		assertEquals(PaisesValues.BURUNDI,PaisesValues.parse(21));
		assertEquals(PaisesValues.BUTAO,PaisesValues.parse(27));
		assertEquals(PaisesValues.CABO_VERDE,PaisesValues.parse(43));
		assertEquals(PaisesValues.CAMAROES,PaisesValues.parse(202));
		assertEquals(PaisesValues.CAMBOJA,PaisesValues.parse(201));
		assertEquals(PaisesValues.CANADA,PaisesValues.parse(31));
		assertEquals(PaisesValues.CANARIAS_ILHAS,PaisesValues.parse(235));
		assertEquals(PaisesValues.CATAR,PaisesValues.parse(150));
		assertEquals(PaisesValues.CAYMAN_ILHAS,PaisesValues.parse(197));
		assertEquals(PaisesValues.CAZAQUISTAO,PaisesValues.parse(99));
		assertEquals(PaisesValues.CHADE,PaisesValues.parse(170));
		assertEquals(PaisesValues.CHILE,PaisesValues.parse(38));
		assertEquals(PaisesValues.CHINA,PaisesValues.parse(39));
		assertEquals(PaisesValues.CHIPRE,PaisesValues.parse(44));
		assertEquals(PaisesValues.CHRISTMAS_ILHA,PaisesValues.parse(218));
		assertEquals(PaisesValues.CINGAPURA,PaisesValues.parse(160));
		assertEquals(PaisesValues.COCOS_ILHAS_KEELING,PaisesValues.parse(32));
		assertEquals(PaisesValues.COLOMBIA,PaisesValues.parse(40));
		assertEquals(PaisesValues.COMORES,PaisesValues.parse(95));
		assertEquals(PaisesValues.CONGO,PaisesValues.parse(34));
		assertEquals(PaisesValues.COOK_ILHAS,PaisesValues.parse(37));
		assertEquals(PaisesValues.COREIA_DO_NORTE,PaisesValues.parse(96));
		assertEquals(PaisesValues.COREIA_DO_SUL,PaisesValues.parse(97));
		assertEquals(PaisesValues.COSTA_DO_MARFIM,PaisesValues.parse(36));
		assertEquals(PaisesValues.COSTA_RICA,PaisesValues.parse(41));
		assertEquals(PaisesValues.CROACIA,PaisesValues.parse(204));
		assertEquals(PaisesValues.CUBA,PaisesValues.parse(42));
		assertEquals(PaisesValues.DINAMARCA,PaisesValues.parse(46));
		assertEquals(PaisesValues.DJIBUTI,PaisesValues.parse(45));
		assertEquals(PaisesValues.DOMINICA,PaisesValues.parse(47));		
		assertEquals(PaisesValues.EGITO,PaisesValues.parse(51));
		assertEquals(PaisesValues.EL_SALVADOR,PaisesValues.parse(167));
		assertEquals(PaisesValues.EMIRADOS_ARABES_UNID,PaisesValues.parse(3));
		assertEquals(PaisesValues.EQUADOR,PaisesValues.parse(50));
		assertEquals(PaisesValues.ERITREIA,PaisesValues.parse(246));
		assertEquals(PaisesValues.ESLOVAQUIA,PaisesValues.parse(206));
		assertEquals(PaisesValues.ESLOVENIA,PaisesValues.parse(205));
		assertEquals(PaisesValues.ESPANHA,PaisesValues.parse(53));
		assertEquals(PaisesValues.ESTADOS_UNIDOS,PaisesValues.parse(182));
		assertEquals(PaisesValues.ESTONIA,PaisesValues.parse(207));
		assertEquals(PaisesValues.ETIOPIA,PaisesValues.parse(54));		
		assertEquals(PaisesValues.FALKLAND_ILHAS_MALV,PaisesValues.parse(58));
		assertEquals(PaisesValues.FEROE_ILHAS,PaisesValues.parse(208));
		assertEquals(PaisesValues.FIJI,PaisesValues.parse(57));
		assertEquals(PaisesValues.FILIPINAS,PaisesValues.parse(209));
		assertEquals(PaisesValues.FINLANDIA,PaisesValues.parse(56));
		assertEquals(PaisesValues.FRANCA,PaisesValues.parse(60));
		assertEquals(PaisesValues.GABAO,PaisesValues.parse(61));
		assertEquals(PaisesValues.GAMBIA,PaisesValues.parse(69));
		assertEquals(PaisesValues.GANA,PaisesValues.parse(66));
		assertEquals(PaisesValues.GEORGIA,PaisesValues.parse(64));
		assertEquals(PaisesValues.GIBRALTAR,PaisesValues.parse(67));
		assertEquals(PaisesValues.GRANADA,PaisesValues.parse(63));
		assertEquals(PaisesValues.GRECIA,PaisesValues.parse(73));
		assertEquals(PaisesValues.GROENLANDIA,PaisesValues.parse(68));
		assertEquals(PaisesValues.GUADALUPE,PaisesValues.parse(71));
		assertEquals(PaisesValues.GUAM,PaisesValues.parse(75));
		assertEquals(PaisesValues.GUATEMALA,PaisesValues.parse(74));		
		assertEquals(PaisesValues.GUERNSEY_ILHAS_DO_C,PaisesValues.parse(65));
		assertEquals(PaisesValues.GUIANA,PaisesValues.parse(76));
		assertEquals(PaisesValues.GUIANA_FRANCESA,PaisesValues.parse(210));
		assertEquals(PaisesValues.GUINE,PaisesValues.parse(70));
		assertEquals(PaisesValues.GUINE_EQUATORIAL,PaisesValues.parse(72));		
		assertEquals(PaisesValues.GUINE_BISSAU,PaisesValues.parse(211));
		assertEquals(PaisesValues.HAITI,PaisesValues.parse(79));
		assertEquals(PaisesValues.HOLANDA,PaisesValues.parse(133));
		assertEquals(PaisesValues.HONDURAS,PaisesValues.parse(78));
		assertEquals(PaisesValues.HONG_KONG,PaisesValues.parse(77));
		assertEquals(PaisesValues.HUNGRIA,PaisesValues.parse(80));		
		assertEquals(PaisesValues.IEMEN,PaisesValues.parse(190));
		assertEquals(PaisesValues.INDIA,PaisesValues.parse(84));
		assertEquals(PaisesValues.INDONESIA,PaisesValues.parse(81));
		assertEquals(PaisesValues.IRA,PaisesValues.parse(212));
		assertEquals(PaisesValues.IRAQUE,PaisesValues.parse(86));
		assertEquals(PaisesValues.IRLANDA,PaisesValues.parse(82));
		assertEquals(PaisesValues.ISLANDIA,PaisesValues.parse(87));
		assertEquals(PaisesValues.ISRAEL,PaisesValues.parse(83));
		assertEquals(PaisesValues.ITALIA,PaisesValues.parse(88));
		assertEquals(PaisesValues.JAMAICA,PaisesValues.parse(90));
		assertEquals(PaisesValues.JAPAO,PaisesValues.parse(92));
		assertEquals(PaisesValues.JERSEY_ILHAS_DO_CAN,PaisesValues.parse(89));
		assertEquals(PaisesValues.JOHNSTON_ILHAS,PaisesValues.parse(233));
		assertEquals(PaisesValues.JORDANIA,PaisesValues.parse(91));		
		assertEquals(PaisesValues.KIRIBATI,PaisesValues.parse(94));
		assertEquals(PaisesValues.KUWAIT,PaisesValues.parse(98));
		assertEquals(PaisesValues.LAOS,PaisesValues.parse(213));
		assertEquals(PaisesValues.LESOTO,PaisesValues.parse(105));
		assertEquals(PaisesValues.LETONIA,PaisesValues.parse(237));
		assertEquals(PaisesValues.LIBANO,PaisesValues.parse(100));
		assertEquals(PaisesValues.LIBERIA,PaisesValues.parse(104));
		assertEquals(PaisesValues.LIBIA,PaisesValues.parse(214));
		assertEquals(PaisesValues.LIECHTENSTEIN,PaisesValues.parse(102));
		assertEquals(PaisesValues.LITUANIA,PaisesValues.parse(106));
		assertEquals(PaisesValues.LUXEMBURGO,PaisesValues.parse(107));
		assertEquals(PaisesValues.MACAU,PaisesValues.parse(117));
		assertEquals(PaisesValues.MACEDONIA,PaisesValues.parse(113));
		assertEquals(PaisesValues.MADAGASCAR,PaisesValues.parse(111));
		assertEquals(PaisesValues.MADEIRA_ILHA,PaisesValues.parse(238));
		assertEquals(PaisesValues.MALASIA,PaisesValues.parse(125));
		assertEquals(PaisesValues.MALAWI,PaisesValues.parse(123));
		assertEquals(PaisesValues.MALDIVAS,PaisesValues.parse(122));
		assertEquals(PaisesValues.MALI,PaisesValues.parse(114));
		assertEquals(PaisesValues.MALTA,PaisesValues.parse(120));
		assertEquals(PaisesValues.MAN_ILHA_DE,PaisesValues.parse(236));
		assertEquals(PaisesValues.MARIANAS_DO_NORTE_I,PaisesValues.parse(215));
		assertEquals(PaisesValues.MARROCOS,PaisesValues.parse(109));
		assertEquals(PaisesValues.MARSHALL_ILHAS,PaisesValues.parse(112));
		assertEquals(PaisesValues.MARTINICA,PaisesValues.parse(216));	
		assertEquals(PaisesValues.MAURICIO,PaisesValues.parse(121));
		assertEquals(PaisesValues.MAURITANIA,PaisesValues.parse(118));
		assertEquals(PaisesValues.MEXICO,PaisesValues.parse(124));
		assertEquals(PaisesValues.MIANMA,PaisesValues.parse(115));
		assertEquals(PaisesValues.MICRONESIA,PaisesValues.parse(59));
		assertEquals(PaisesValues.MIDWAY_ILHAS,PaisesValues.parse(232));
		assertEquals(PaisesValues.MOCAMBIQUE,PaisesValues.parse(126));
		assertEquals(PaisesValues.MOLDAVIA,PaisesValues.parse(217));
		assertEquals(PaisesValues.MONACO,PaisesValues.parse(110));
		assertEquals(PaisesValues.MONGOLIA,PaisesValues.parse(116));
		assertEquals(PaisesValues.MONTSERRAT,PaisesValues.parse(119));
		assertEquals(PaisesValues.NAMIBIA,PaisesValues.parse(127));
		assertEquals(PaisesValues.NAURU,PaisesValues.parse(136));
		assertEquals(PaisesValues.NEPAL,PaisesValues.parse(135));
		assertEquals(PaisesValues.NICARAGUA,PaisesValues.parse(132));
		assertEquals(PaisesValues.NIGER,PaisesValues.parse(129));
		assertEquals(PaisesValues.NIGERIA,PaisesValues.parse(131));
		assertEquals(PaisesValues.NIUE,PaisesValues.parse(137));
		assertEquals(PaisesValues.NORFOLK_ILHA,PaisesValues.parse(130));
		assertEquals(PaisesValues.NORUEGA,PaisesValues.parse(134));
		assertEquals(PaisesValues.NOVA_CALEDONIA,PaisesValues.parse(128));
		assertEquals(PaisesValues.NOVA_ZELANDIA,PaisesValues.parse(138));
		assertEquals(PaisesValues.OMA,PaisesValues.parse(139));
		assertEquals(PaisesValues.ORGANIZACOES_INTERNA,PaisesValues.parse(243));
		assertEquals(PaisesValues.PACIFICO_ILHAS_DO,PaisesValues.parse(239));
		assertEquals(PaisesValues.PALAU,PaisesValues.parse(147));
		assertEquals(PaisesValues.PANAMA,PaisesValues.parse(140));
		assertEquals(PaisesValues.PAPUA_NOVA_GUINE,PaisesValues.parse(219));
		assertEquals(PaisesValues.PAQUISTAO,PaisesValues.parse(143));
		assertEquals(PaisesValues.PARAGUAI,PaisesValues.parse(148));
		assertEquals(PaisesValues.PERU,PaisesValues.parse(141));
		assertEquals(PaisesValues.PITCAIRN_ILHA,PaisesValues.parse(220));
		assertEquals(PaisesValues.POLINESIA_FRANCESA,PaisesValues.parse(142));
		assertEquals(PaisesValues.POLONIA,PaisesValues.parse(144));
		assertEquals(PaisesValues.PORTO_RICO,PaisesValues.parse(145));
		assertEquals(PaisesValues.PORTUGAL,PaisesValues.parse(146));		
		assertEquals(PaisesValues.QUENIA,PaisesValues.parse(93));
		assertEquals(PaisesValues.QUIRGUISTAO,PaisesValues.parse(231));
		assertEquals(PaisesValues.REINO_UNIDO,PaisesValues.parse(62));
		assertEquals(PaisesValues.REP_DEMOCRATICA_DO_C,PaisesValues.parse(194));
		assertEquals(PaisesValues.REPUBLICA_CENTRO_AFR,PaisesValues.parse(33));
		assertEquals(PaisesValues.REPUBLICA_DOMINICANA,PaisesValues.parse(48));
		assertEquals(PaisesValues.REPUBLICA_TCHECA,PaisesValues.parse(230));
		assertEquals(PaisesValues.REUNIAO,PaisesValues.parse(151));
		assertEquals(PaisesValues.ROMENIA,PaisesValues.parse(152));
		assertEquals(PaisesValues.RUANDA,PaisesValues.parse(154));		
		assertEquals(PaisesValues.RUSSIA,PaisesValues.parse(153));
		assertEquals(PaisesValues.SAARA_OCIDENTAL,PaisesValues.parse(52));
		assertEquals(PaisesValues.SALOMAO_ILHAS,PaisesValues.parse(156));
		assertEquals(PaisesValues.SAMOA,PaisesValues.parse(245));
		assertEquals(PaisesValues.SAMOA_AMERICANA,PaisesValues.parse(222));
		assertEquals(PaisesValues.SAN_MARINO,PaisesValues.parse(163));
		assertEquals(PaisesValues.SANTA_HELENA,PaisesValues.parse(161));
		assertEquals(PaisesValues.SANTA_LUCIA,PaisesValues.parse(101));
		assertEquals(PaisesValues.SAO_CRISTOVAO_E_NEVI,PaisesValues.parse(221));
		assertEquals(PaisesValues.SAO_PEDRO_E_MIQUELON,PaisesValues.parse(223));
		assertEquals(PaisesValues.SAO_TOME_E_PRINCIPE,PaisesValues.parse(225));
		assertEquals(PaisesValues.SAO_VICENTE_E_GRANAD,PaisesValues.parse(224));
		assertEquals(PaisesValues.SENEGAL,PaisesValues.parse(164));
		assertEquals(PaisesValues.SERRA_LEOA,PaisesValues.parse(162));
		assertEquals(PaisesValues.SERVIA_E_MONTENEGRO,PaisesValues.parse(191));
		assertEquals(PaisesValues.SEYCHELLES,PaisesValues.parse(157));
		assertEquals(PaisesValues.SIRIA,PaisesValues.parse(198));
		assertEquals(PaisesValues.SOMALIA,PaisesValues.parse(165));
		assertEquals(PaisesValues.SRI_LANKA,PaisesValues.parse(103));
		assertEquals(PaisesValues.SUAZILANDIA,PaisesValues.parse(168));
		assertEquals(PaisesValues.SUDAO,PaisesValues.parse(158));
		assertEquals(PaisesValues.SUECIA,PaisesValues.parse(159));
		assertEquals(PaisesValues.SUICA,PaisesValues.parse(35));
		assertEquals(PaisesValues.SURINAME,PaisesValues.parse(166));
		assertEquals(PaisesValues.TADJIQUISTAO,PaisesValues.parse(226));
		assertEquals(PaisesValues.TAILANDIA,PaisesValues.parse(172));
		assertEquals(PaisesValues.TAIWAN,PaisesValues.parse(203));
		assertEquals(PaisesValues.TANZANIA,PaisesValues.parse(179));
		assertEquals(PaisesValues.TERRIT_BRIT_OCEANO_I,PaisesValues.parse(85));
		assertEquals(PaisesValues.TIMOR_LESTE,PaisesValues.parse(176));
		assertEquals(PaisesValues.TOGO,PaisesValues.parse(171));
		assertEquals(PaisesValues.TONGA,PaisesValues.parse(175));
		assertEquals(PaisesValues.TOQUELAU_ILHAS,PaisesValues.parse(227));
		assertEquals(PaisesValues.TRINIDAD_E_TOBAGO,PaisesValues.parse(228));
		assertEquals(PaisesValues.TUNISIA,PaisesValues.parse(174));
		assertEquals(PaisesValues.TURCAS_E_CAICOS,PaisesValues.parse(169));
		assertEquals(PaisesValues.TURCOMENISTAO,PaisesValues.parse(173));
		assertEquals(PaisesValues.TURQUIA,PaisesValues.parse(177));
		assertEquals(PaisesValues.TUVALU,PaisesValues.parse(178));
		assertEquals(PaisesValues.UCRANIA,PaisesValues.parse(180));
		assertEquals(PaisesValues.UGANDA,PaisesValues.parse(181));
		assertEquals(PaisesValues.URUGUAI,PaisesValues.parse(183));
		assertEquals(PaisesValues.UZBEQUISTAO,PaisesValues.parse(184));
		assertEquals(PaisesValues.VANUATU,PaisesValues.parse(189));
		assertEquals(PaisesValues.VATICANO,PaisesValues.parse(185));
		assertEquals(PaisesValues.VENEZUELA,PaisesValues.parse(186));
		assertEquals(PaisesValues.VIETNA,PaisesValues.parse(229));
		assertEquals(PaisesValues.VIRGENS_ILHAS,PaisesValues.parse(187));
		assertEquals(PaisesValues.VIRGENS_ILHAS_EUA,PaisesValues.parse(188));
		assertEquals(PaisesValues.WAKE_ILHA,PaisesValues.parse(247));
		assertEquals(PaisesValues.ZAMBIA,PaisesValues.parse(193));
		assertEquals(PaisesValues.ZIMBABWE,PaisesValues.parse(195));
		assertEquals(PaisesValues.ZONA_DO_CANAL_DO_PAN,PaisesValues.parse(149));
	}	
	
}
